using System;
using System.Collections.Generic;
using Beebyte.Obfuscator;
using UnityEngine;

// Token: 0x02000016 RID: 22
[ObfuscateLiterals]
[Serializable]
public class ActorStatsLibrary : AssetLibrary<ActorStats>
{
	// Token: 0x060000BF RID: 191 RVA: 0x00007F48 File Offset: 0x00006148
	public override void init()
	{
		Debug.Log("INIT ActorStats");
		base.init();
		ActorStats actorStats = new ActorStats();
		actorStats.id = "_unit";
		actorStats.canBeKilledByStuff = true;
		actorStats.canBeKilledByLifeEraser = true;
		actorStats.canAttackBuildings = true;
		actorStats.unit = true;
		actorStats.swimToIsland = true;
		actorStats.canBeMovedByPowers = true;
		actorStats.canBeHurtByPowers = true;
		actorStats.canTurnIntoZombie = true;
		actorStats.updateZ = true;
		actorStats.effectDamage = true;
		actorStats.flipAnimation = true;
		actorStats.actorSize = ActorSize.S13_Human;
		actorStats.canBeInspected = true;
		actorStats.hideOnMinimap = true;
		actorStats.use_items = true;
		actorStats.take_items = true;
		actorStats.needFood = true;
		actorStats.diet_meat = true;
		actorStats.inspect_home = true;
		actorStats.disableJumpAnimation = false;
		actorStats.deathAnimationAngle = true;
		actorStats.prefab = "p_unit";
		actorStats.body_separate_part_head = true;
		actorStats.body_separate_part_hands = true;
		actorStats.canHaveStatusEffect = true;
		actorStats.sprite_group_renderer = true;
		actorStats.have_soul = true;
		actorStats.landCreature = true;
		ActorStats pAsset = actorStats;
		this.t = actorStats;
		this.add(pAsset);
		this.t.canTurnIntoMush = true;
		this.t.mushID = "mush_unit";
		this.t.canTurnIntoTumorMonster = true;
		this.t.tumorMonsterID = "tumor_monster_unit";
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.animation_walk_speed = 0.1f;
		this.t.animation_swim_speed = 0.1f;
		this.t.job = "unit";
		this.t.baseStats.speed = 100f;
		this.t.baseStats.attackSpeed = 60f;
		this.t.defaultAttack = "hands";
		this.t.skeletonID = "skeleton_cursed";
		this.t.disableJumpAnimation = true;
		this.clone("unit_human", "_unit");
		this.t.nameLocale = "Humans";
		this.t.nameTemplate = "human_name";
		this.t.race = "human";
		this.t.maxAge = 70;
		this.t.icon = "iconHumans";
		this.t.color = Toolbox.makeColor("#005E72");
		this.t.zombieID = "zombie";
		this.t.setBaseStats(100, 15, 40, 0, 5, 92, 0);
		this.t.disableJumpAnimation = true;
		this.t.heads = 11;
		this.addColorSet("default", "#FFC984", "#543E2C");
		this.clone("unit_elf", "_unit");
		this.t.nameLocale = "Elves";
		this.t.nameTemplate = "elf_name";
		this.t.race = "elf";
		this.t.maxAge = 200;
		this.t.icon = "iconElves";
		this.t.color = Toolbox.makeColor("#005D00");
		this.t.zombieID = "zombie_elf";
		this.addTrait("weightless");
		this.t.setBaseStats(120, 15, 50, 0, 10, 95, 0);
		ActorStats t = this.t;
		t.action_death = (WorldAction)Delegate.Combine(t.action_death, new WorldAction(ActionLibrary.tryToGrowBiomeGrass));
		ActorStats t2 = this.t;
		t2.action_death = (WorldAction)Delegate.Combine(t2.action_death, new WorldAction(ActionLibrary.tryToGrowTree));
		this.t.disableJumpAnimation = true;
		this.t.heads = 7;
		this.addColorSet("default", "#FFC984", "#543E2C");
		this.clone("unit_orc", "_unit");
		this.t.nameLocale = "Orcs";
		this.t.nameTemplate = "orc_name";
		this.t.race = "orc";
		this.t.maxAge = 50;
		this.t.icon = "iconOrcs";
		this.t.color = Toolbox.makeColor("#2F5225");
		this.t.zombieID = "zombie_orc";
		this.addTrait("regeneration");
		this.addTrait("savage");
		this.t.setBaseStats(170, 20, 50, 3, 0, 90, 0);
		this.t.disableJumpAnimation = true;
		this.t.heads = 7;
		this.addColorSet("default", "#5C823C", "#2D3724");
		this.clone("unit_dwarf", "_unit");
		this.t.nameLocale = "Dwarves";
		this.t.nameTemplate = "dwarf_name";
		this.t.race = "dwarf";
		this.t.maxAge = 110;
		this.t.baseStats.attackSpeed = 50f;
		this.t.icon = "iconDwarf";
		this.t.color = Toolbox.makeColor("#828282");
		this.t.zombieID = "zombie_dwarf";
		this.t.setBaseStats(150, 17, 30, 4, 0, 90, 0);
		this.addTrait("miner");
		this.t.disableJumpAnimation = true;
		this.t.heads = 7;
		this.addColorSet("default", "#FFC984", "#543E2C");
		this.clone("baby_human", "unit_human");
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = false;
		this.t.take_items = false;
		this.t.baseStats.speed = 10f;
		this.t.timeToGrow = 200;
		this.t.baby = true;
		this.t.animation_idle = "walk_3";
		this.addTrait("peaceful");
		this.t.growIntoID = "unit_human";
		this.t.disableJumpAnimation = true;
		this.t.color_sets = this.get("unit_human").color_sets;
		this.clone("baby_elf", "unit_elf");
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = false;
		this.t.take_items = false;
		this.t.baseStats.speed = 10f;
		this.t.timeToGrow = 400;
		this.t.baby = true;
		this.t.animation_idle = "walk_3";
		this.t.growIntoID = "unit_elf";
		this.addTrait("peaceful");
		ActorStats t3 = this.t;
		t3.action_death = (WorldAction)Delegate.Combine(t3.action_death, new WorldAction(ActionLibrary.tryToGrowBiomeGrass));
		ActorStats t4 = this.t;
		t4.action_death = (WorldAction)Delegate.Combine(t4.action_death, new WorldAction(ActionLibrary.tryToCreatePlants));
		this.t.disableJumpAnimation = true;
		this.t.color_sets = this.get("unit_elf").color_sets;
		this.clone("baby_orc", "unit_orc");
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = false;
		this.t.take_items = false;
		this.t.baseStats.speed = 10f;
		this.t.timeToGrow = 120;
		this.t.baby = true;
		this.t.animation_idle = "walk_3";
		this.t.growIntoID = "unit_orc";
		this.addTrait("peaceful");
		this.t.disableJumpAnimation = true;
		this.t.color_sets = this.get("unit_orc").color_sets;
		this.clone("baby_dwarf", "unit_dwarf");
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = false;
		this.t.take_items = false;
		this.t.baseStats.speed = 10f;
		this.t.timeToGrow = 250;
		this.t.baby = true;
		this.t.animation_idle = "walk_3";
		this.t.growIntoID = "unit_dwarf";
		this.addTrait("peaceful");
		this.t.disableJumpAnimation = true;
		this.t.color_sets = this.get("unit_dwarf").color_sets;
		ActorStats actorStats2 = new ActorStats();
		actorStats2.id = "antBlack";
		actorStats2.race = "special";
		actorStats2.kingdom = "ants";
		actorStats2.canBeKilledByStuff = true;
		actorStats2.canBeKilledByLifeEraser = true;
		actorStats2.ignoreTileSpeedMod = true;
		actorStats2.skipFightLogic = true;
		actorStats2.ignoreJobs = true;
		actorStats2.canBeMovedByPowers = true;
		actorStats2.canBeHurtByPowers = true;
		actorStats2.updateZ = true;
		actorStats2.effectDamage = true;
		actorStats2.flipAnimation = true;
		actorStats2.actorSize = ActorSize.S13_Human;
		actorStats2.hideOnMinimap = true;
		actorStats2.prefab = "p_unit";
		actorStats2.color = Toolbox.makeColor("#000000");
		actorStats2.canHaveStatusEffect = true;
		actorStats2.dieOnBlocks = false;
		actorStats2.moveFromBlock = false;
		actorStats2.sprite_group_renderer = true;
		pAsset = actorStats2;
		this.t = actorStats2;
		this.add(pAsset);
		this.t.canBeInspected = true;
		this.addFlag("ant");
		this.t.nameLocale = "Black Ant";
		this.t.nameTemplate = "ant_name";
		this.t.texture_path = "t_antBlack";
		this.t.animation_walk = "walk_0";
		this.t.baseStats.speed = 40f;
		this.t.baseStats.knockback = 0f;
		this.addTrait("strong_minded");
		this.clone("antGreen", "antBlack");
		this.t.nameLocale = "Green Ant";
		this.t.texture_path = "t_antGreen";
		this.t.color = Toolbox.makeColor("#007F0E");
		this.clone("antBlue", "antBlack");
		this.t.nameLocale = "Blue Ant";
		this.t.texture_path = "t_antBlue";
		this.t.color = Toolbox.makeColor("#0094FF");
		this.clone("antRed", "antBlack");
		this.t.nameLocale = "Red Ant";
		this.t.texture_path = "t_antRed";
		this.t.color = Toolbox.makeColor("#FF2511");
		this.clone("sandSpider", "antBlack");
		this.t.nameLocale = "Sand Spider";
		this.t.texture_path = "t_sandSpider";
		this.t.color = Toolbox.makeColor("#2D2D2D");
		this.t.baseStats.speed = 100f;
		this.clone("worm", "antBlack");
		this.t.canBeInspected = false;
		this.t.nameTemplate = "bug_name";
		this.t.nameLocale = "Worm";
		this.t.animation_walk = "walk_0";
		this.t.canBeMovedByPowers = false;
		this.t.canBeHurtByPowers = true;
		this.t.canBeKilledByStuff = false;
		this.t.race = "special";
		this.t.baseStats.speed = 100f;
		this.t.color.a = 0;
		this.t.shadow = false;
		this.t.texture_path = "t_worm";
		this.addTrait("fire_proof");
		ActorStats actorStats3 = new ActorStats();
		actorStats3.id = "printer";
		actorStats3.race = "nature";
		actorStats3.kingdom = "nature";
		actorStats3.canBeKilledByLifeEraser = true;
		actorStats3.ignoreTileSpeedMod = true;
		actorStats3.skipFightLogic = true;
		actorStats3.ignoreJobs = true;
		actorStats3.canBeMovedByPowers = false;
		actorStats3.canBeHurtByPowers = true;
		actorStats3.updateZ = true;
		actorStats3.effectDamage = true;
		actorStats3.flipAnimation = true;
		actorStats3.hideOnMinimap = true;
		actorStats3.needFood = false;
		actorStats3.skipSave = true;
		actorStats3.prefab = "p_unit";
		actorStats3.canHaveStatusEffect = true;
		actorStats3.dieOnBlocks = false;
		actorStats3.moveFromBlock = false;
		actorStats3.ignoredByInfinityCoin = true;
		pAsset = actorStats3;
		this.t = actorStats3;
		this.add(pAsset);
		this.addFlag("ant");
		this.t.nameLocale = "Printer";
		this.t.texture_path = "t_printer";
		this.t.baseStats.health = 1;
		this.t.baseStats.speed = 10000f;
		this.t.animation_walk = "walk_0,walk_1,walk_2";
		ActorStats actorStats4 = new ActorStats();
		actorStats4.id = "dragon";
		actorStats4.race = "dragon";
		actorStats4.kingdom = "dragons";
		actorStats4.canBeKilledByStuff = true;
		actorStats4.canBeKilledByLifeEraser = true;
		actorStats4.ignoreTileSpeedMod = true;
		actorStats4.skipFightLogic = true;
		actorStats4.ignoreJobs = true;
		actorStats4.canBeMovedByPowers = true;
		actorStats4.canBeHurtByPowers = true;
		actorStats4.updateZ = true;
		actorStats4.defaultZ = 0f;
		actorStats4.effectDamage = true;
		actorStats4.flipAnimation = true;
		actorStats4.specialAnimation = true;
		actorStats4.specialDeadAnimation = true;
		actorStats4.canTurnIntoZombie = true;
		actorStats4.zombieID = "zombie_dragon";
		actorStats4.actorSize = ActorSize.S17_Dragon;
		actorStats4.shadowTexture = "unitShadow_7";
		actorStats4.canBeInspected = true;
		actorStats4.hideFavoriteIcon = true;
		actorStats4.icon = "iconDragon";
		actorStats4.inspectAvatarScale = 1.5f;
		actorStats4.prefab = "p_dragon";
		actorStats4.needFood = false;
		actorStats4.dieOnBlocks = false;
		actorStats4.moveFromBlock = false;
		pAsset = actorStats4;
		this.t = actorStats4;
		this.add(pAsset);
		this.t.nameLocale = "Dragon";
		this.t.dieInLava = false;
		this.t.baseStats.scale = 0.3f;
		this.t.baseStats.size = 2f;
		this.t.baseStats.health = 1000;
		this.t.baseStats.speed = 60f;
		this.t.baseStats.attackSpeed = 100f;
		this.t.baseStats.damage = 80;
		this.t.baseStats.knockback = 0.6f;
		ActorStats t5 = this.t;
		t5.action_death = (WorldAction)Delegate.Combine(t5.action_death, new WorldAction(ActionLibrary.dragonDeath));
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.addTrait("strong_minded");
		this.addTrait("fire_proof");
		this.addTrait("fire_blood");
		this.clone("zombie_dragon", "dragon");
		this.t.nameLocale = "Zombie";
		this.t.prefab = "p_zombie_dragon";
		this.t.nameLocale = "Zombie";
		this.t.dieInLava = true;
		this.setZombie();
		this.removeTrait("fire_proof");
		this.removeTrait("fire_blood");
		this.addTrait("acid_blood");
		this.addTrait("acid_proof");
		ActorStats actorStats5 = new ActorStats();
		actorStats5.id = "UFO";
		actorStats5.kingdom = "aliens";
		actorStats5.race = "ufo";
		actorStats5.canBeKilledByStuff = true;
		actorStats5.canBeKilledByLifeEraser = true;
		actorStats5.ignoreTileSpeedMod = true;
		actorStats5.skipFightLogic = true;
		actorStats5.ignoreJobs = true;
		actorStats5.flying = true;
		actorStats5.very_high_flyer = true;
		actorStats5.canBeMovedByPowers = true;
		actorStats5.canBeHurtByPowers = true;
		actorStats5.effectDamage = true;
		actorStats5.specialAnimation = true;
		actorStats5.specialDeadAnimation = true;
		actorStats5.actorSize = ActorSize.S17_Dragon;
		actorStats5.shadowTexture = "unitShadow_7";
		actorStats5.canBeInspected = true;
		actorStats5.icon = "iconUfo";
		actorStats5.needFood = false;
		actorStats5.hideFavoriteIcon = true;
		actorStats5.dieByLightning = true;
		actorStats5.prefab = "p_ufo";
		actorStats5.dieOnBlocks = false;
		actorStats5.moveFromBlock = false;
		actorStats5.have_skin = false;
		actorStats5.flag_ufo = true;
		pAsset = actorStats5;
		this.t = actorStats5;
		this.add(pAsset);
		this.t.nameLocale = "UFO";
		this.t.nameTemplate = "ufo_name";
		this.t.baseStats.scale = 0.3f;
		this.t.baseStats.health = 500;
		this.t.baseStats.speed = 200f;
		this.t.baseStats.attackSpeed = 100f;
		this.t.baseStats.damage = 80;
		this.t.baseStats.knockback = 0.6f;
		ActorStats t6 = this.t;
		t6.action_death = (WorldAction)Delegate.Combine(t6.action_death, new WorldAction(ActionLibrary.spawnAliens));
		this.addTrait("immortal");
		this.addTrait("strong_minded");
		this.addTrait("fire_proof");
		ActorStats actorStats6 = new ActorStats();
		actorStats6.id = "boulder";
		actorStats6.race = "nature";
		actorStats6.kingdom = "nature";
		actorStats6.ignoreTileSpeedMod = true;
		actorStats6.skipFightLogic = true;
		actorStats6.ignoreJobs = true;
		actorStats6.canBeMovedByPowers = true;
		actorStats6.canBeHurtByPowers = true;
		actorStats6.updateZ = true;
		actorStats6.effectDamage = true;
		actorStats6.specialAnimation = true;
		actorStats6.specialDeadAnimation = true;
		actorStats6.needFood = false;
		actorStats6.skipSave = true;
		actorStats6.prefab = "p_boulder";
		actorStats6.dieOnBlocks = false;
		actorStats6.moveFromBlock = false;
		actorStats6.ignoredByInfinityCoin = true;
		pAsset = actorStats6;
		this.t = actorStats6;
		this.add(pAsset);
		this.t.nameLocale = "Bowling Ball";
		this.t.baseStats.scale = 0.3f;
		ActorStats actorStats7 = new ActorStats();
		actorStats7.id = "tornado";
		actorStats7.race = "nature";
		actorStats7.kingdom = "nature";
		actorStats7.canBeKilledByLifeEraser = true;
		actorStats7.ignoreTileSpeedMod = true;
		actorStats7.skipFightLogic = true;
		actorStats7.ignoreJobs = true;
		actorStats7.flying = true;
		actorStats7.canBeMovedByPowers = true;
		actorStats7.canBeHurtByPowers = true;
		actorStats7.updateZ = true;
		actorStats7.flipAnimation = true;
		actorStats7.specialAnimation = true;
		actorStats7.specialDeadAnimation = true;
		actorStats7.needFood = false;
		actorStats7.skipSave = true;
		actorStats7.prefab = "p_tornado";
		actorStats7.dieOnBlocks = false;
		actorStats7.moveFromBlock = false;
		actorStats7.ignoredByInfinityCoin = true;
		actorStats7.flag_tornado = true;
		pAsset = actorStats7;
		this.t = actorStats7;
		this.add(pAsset);
		this.t.nameLocale = "Tornado";
		this.t.baseStats.scale = 0f;
		this.t.baseStats.speed = 50f;
		this.t.baseStats.attackSpeed = 100f;
		this.t.baseStats.damage = 7;
		this.addTrait("strong_minded");
		ActorStats actorStats8 = new ActorStats();
		actorStats8.id = "crabzilla";
		actorStats8.race = "crabzilla";
		actorStats8.kingdom = "crabzilla";
		actorStats8.canBeKilledByStuff = true;
		actorStats8.ignoreTileSpeedMod = true;
		actorStats8.skipFightLogic = true;
		actorStats8.ignoreJobs = true;
		actorStats8.flying = false;
		actorStats8.canBeMovedByPowers = false;
		actorStats8.canBeHurtByPowers = true;
		actorStats8.updateZ = true;
		actorStats8.flipAnimation = false;
		actorStats8.specialAnimation = true;
		actorStats8.specialDeadAnimation = true;
		actorStats8.needFood = false;
		actorStats8.skipSave = true;
		actorStats8.prefab = "p_crabzilla";
		actorStats8.dieOnBlocks = false;
		actorStats8.moveFromBlock = false;
		actorStats8.ignoredByInfinityCoin = true;
		pAsset = actorStats8;
		this.t = actorStats8;
		this.add(pAsset);
		this.t.haveSpriteRenderer = false;
		this.t.nameLocale = "Crabzilla";
		this.t.baseStats.scale = 0.25f;
		this.t.actorSize = ActorSize.S17_Dragon;
		this.t.baseStats.health = 5000;
		this.t.baseStats.speed = 50f;
		this.t.baseStats.attackSpeed = 100f;
		this.t.baseStats.damage = 7;
		this.t.baseStats.size = 8f;
		this.t.canLevelUp = false;
		this.t.shadow = false;
		this.t.hit_fx_alternative_offset = false;
		ActorStats t7 = this.t;
		t7.action_death = (WorldAction)Delegate.Combine(t7.action_death, new WorldAction(ActionLibrary.startNuke));
		this.addTrait("strong_minded");
		ActorStats actorStats9 = new ActorStats();
		actorStats9.id = "godFinger";
		actorStats9.actorSize = ActorSize.S17_Dragon;
		actorStats9.shadowTexture = "unitShadow_7";
		actorStats9.race = "special";
		actorStats9.kingdom = "godfinger";
		actorStats9.canBeKilledByStuff = true;
		actorStats9.ignoreTileSpeedMod = true;
		actorStats9.canBeKilledByLifeEraser = true;
		actorStats9.skipFightLogic = true;
		actorStats9.ignoreJobs = true;
		actorStats9.canBeMovedByPowers = true;
		actorStats9.canBeHurtByPowers = true;
		actorStats9.updateZ = true;
		actorStats9.effectDamage = true;
		actorStats9.specialAnimation = true;
		actorStats9.needFood = false;
		actorStats9.skipSave = true;
		actorStats9.deathAnimationAngle = true;
		actorStats9.prefab = "p_godFinger";
		actorStats9.dieOnBlocks = false;
		actorStats9.moveFromBlock = false;
		pAsset = actorStats9;
		this.t = actorStats9;
		this.add(pAsset);
		this.t.flag_finger = true;
		this.t.nameLocale = "God Finger";
		this.t.baseStats.scale = 0.3f;
		this.t.baseStats.health = 30;
		this.t.baseStats.damage = 10;
		this.t.damagedByOcean = false;
		this.t.dieInLava = false;
		this.addTrait("strong_minded");
		this.addTrait("fire_proof");
		ActorStats actorStats10 = new ActorStats();
		actorStats10.id = "santa";
		actorStats10.race = "special";
		actorStats10.kingdom = "santa";
		actorStats10.ignoreTileSpeedMod = true;
		actorStats10.skipFightLogic = true;
		actorStats10.ignoreJobs = true;
		actorStats10.flying = true;
		actorStats10.very_high_flyer = true;
		actorStats10.canBeMovedByPowers = true;
		actorStats10.canBeHurtByPowers = true;
		actorStats10.effectDamage = true;
		actorStats10.dieByLightning = true;
		actorStats10.skipSave = true;
		actorStats10.prefab = "p_santa";
		pAsset = actorStats10;
		this.t = actorStats10;
		this.add(pAsset);
		this.t.nameLocale = "Robot Santa";
		this.t.baseStats.health = 50;
		this.t.baseStats.damage = 10;
		this.t.baseStats.speed = 60f;
		this.t.baseStats.size = 2f;
		this.addTrait("strong_minded");
		this.addTrait("immune");
		this.addTrait("evil");
		ActorStats actorStats11 = new ActorStats();
		actorStats11.id = "_mob";
		actorStats11.canBeKilledByStuff = true;
		actorStats11.canBeKilledByLifeEraser = true;
		actorStats11.canAttackBuildings = true;
		actorStats11.swimToIsland = true;
		actorStats11.canBeMovedByPowers = true;
		actorStats11.canBeHurtByPowers = true;
		actorStats11.updateZ = true;
		actorStats11.effectDamage = true;
		actorStats11.flipAnimation = true;
		actorStats11.canBeInspected = true;
		actorStats11.hideOnMinimap = true;
		actorStats11.deathAnimationAngle = true;
		actorStats11.prefab = "p_unit";
		actorStats11.inspect_children = false;
		actorStats11.canHaveStatusEffect = true;
		actorStats11.sprite_group_renderer = true;
		actorStats11.landCreature = true;
		pAsset = actorStats11;
		this.t = actorStats11;
		this.add(pAsset);
		this.t.canTurnIntoMush = true;
		this.t.mushID = "mush_unit";
		this.t.canTurnIntoTumorMonster = true;
		this.t.tumorMonsterID = "tumor_monster_unit";
		this.t.defaultAttack = "base";
		this.t.job = "random_move";
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_2,walk_1";
		this.t.animation_swim = "swim_0,swim_1,swim_1,swim_2";
		this.t.disableJumpAnimation = true;
		this.clone("_animal", "_mob");
		this.t.canTurnIntoMush = true;
		this.t.mushID = "mush_animal";
		this.t.canTurnIntoTumorMonster = true;
		this.t.tumorMonsterID = "tumor_monster_animal";
		this.t.inspect_children = true;
		this.t.needFood = true;
		this.t.job = "animal";
		this.t.animal = true;
		this.t.procreate = true;
		this.t.source_meat = true;
		this.t.defaultAttack = "jaws";
		this.t.maxAge = 100;
		ActorStats actorStats12 = new ActorStats();
		actorStats12.id = "_peacefulAnimal";
		actorStats12.kingdom = "neutral_animals";
		actorStats12.canBeKilledByStuff = true;
		actorStats12.canBeKilledByLifeEraser = true;
		actorStats12.swimToIsland = true;
		actorStats12.procreate = true;
		actorStats12.canBeMovedByPowers = true;
		actorStats12.canBeHurtByPowers = true;
		actorStats12.updateZ = true;
		actorStats12.effectDamage = true;
		actorStats12.flipAnimation = true;
		actorStats12.needFood = true;
		actorStats12.canBeInspected = true;
		actorStats12.hideOnMinimap = true;
		actorStats12.animal = true;
		actorStats12.deathAnimationAngle = true;
		actorStats12.prefab = "p_unit";
		actorStats12.canHaveStatusEffect = true;
		actorStats12.sprite_group_renderer = true;
		actorStats12.landCreature = true;
		pAsset = actorStats12;
		this.t = actorStats12;
		this.add(pAsset);
		this.t.canTurnIntoMush = true;
		this.t.mushID = "mush_animal";
		this.t.canTurnIntoTumorMonster = true;
		this.t.tumorMonsterID = "tumor_monster_animal";
		this.t.maxAge = 200;
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_2,walk_1";
		this.t.animation_swim = "swim_0,swim_1,swim_1,swim_2";
		this.t.baseStats.damage = 1;
		this.addTrait("peaceful");
		this.t.job = "animal";
		this.clone("_carnivore", "_animal");
		this.t.needFood = true;
		this.t.diet_meat = true;
		this.t.diet_meat_insect = true;
		this.clone("_herbivore", "_peacefulAnimal");
		this.t.needFood = true;
		this.t.diet_grass = true;
		this.t.diet_flowers = true;
		this.t.diet_crops = true;
		this.t.diet_berries = true;
		this.t.diet_meat_insect = true;
		this.clone("_omnivore", "_animal");
		this.t.needFood = true;
		this.t.diet_meat = true;
		this.t.diet_meat_insect = true;
		this.t.diet_grass = false;
		this.t.diet_flowers = true;
		this.t.diet_crops = true;
		this.t.diet_berries = true;
		this.clone("sheep", "_herbivore");
		this.t.nameLocale = "Sheeps";
		this.t.nameTemplate = "sheep_name";
		this.t.baseStats.speed = 30f;
		this.t.race = "sheep";
		this.t.diet_grass = true;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S11_Sheep;
		this.t.icon = "iconSheep";
		this.t.color = Toolbox.makeColor("#D7D7D7");
		this.t.baseStats.damage = 5;
		this.t.job = "animal_herd";
		this.t.texture_path = "t_sheep";
		this.t.playRandomSound = true;
		this.t.playRandomSound_id = "sheep";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_sheep";
		this.addColorSet("default", "#BFBFBF", "#FFFFFF");
		this.addColorSet("default", "#825D45", "#2D2D2D");
		this.addColorSet("mushroom", "#C902A1", "#FFDB2B");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.clone("zombie_sheep", "sheep");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_sheep";
		this.setZombie();
		this.clone("cow", "_herbivore");
		this.t.nameLocale = "Cow";
		this.t.kingdom = "neutral_animals";
		this.t.nameTemplate = "cow_name";
		this.t.baseStats.speed = 30f;
		this.t.race = "cow";
		this.t.diet_grass = true;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S14_Cow;
		this.t.shadowTexture = "unitShadow_6";
		this.t.icon = "iconCow";
		this.t.color = Toolbox.makeColor("#D7D7D7");
		this.t.baseStats.damage = 5;
		this.t.job = "animal";
		this.t.texture_path = "t_cow";
		this.t.playRandomSound = false;
		this.t.playRandomSound_id = "cow";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_cow";
		this.clone("zombie_cow", "cow");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_cow";
		this.setZombie();
		this.clone("penguin", "_animal");
		this.t.nameLocale = "Penguin";
		this.t.job = "animal_water_eater";
		this.t.nameTemplate = "penguin_name";
		this.t.needFood = true;
		this.t.swimToIsland = false;
		this.t.speedModLiquid = 30f;
		this.t.kingdom = "neutral_animals";
		this.t.baseStats.speed = 15f;
		this.t.race = "penguin";
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S10_Dog;
		this.t.shadowTexture = "unitShadow_3";
		this.t.icon = "iconPenguin";
		this.t.color = Toolbox.makeColor("#D7D7D7");
		this.t.baseStats.damage = 5;
		this.t.texture_path = "t_penguin";
		this.t.playRandomSound = false;
		this.t.playRandomSound_id = "penguin";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_penguin";
		this.addTrait("weightless");
		this.clone("zombie_penguin", "penguin");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_penguin";
		this.setZombie();
		this.clone("turtle", "_animal");
		this.t.nameLocale = "Turtle";
		this.t.nameTemplate = "turtle_name";
		this.t.job = "animal_water_eater";
		this.t.needFood = true;
		this.t.swimToIsland = false;
		this.t.speedModLiquid = 40f;
		this.t.kingdom = "neutral_animals";
		this.t.baseStats.speed = 5f;
		this.t.race = "turtle";
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S7_Cat;
		this.t.shadowTexture = "unitShadow_7";
		this.t.icon = "iconTurtle";
		this.t.color = Toolbox.makeColor("#D7D7D7");
		this.t.baseStats.damage = 5;
		this.t.texture_path = "t_turtle";
		this.t.playRandomSound = false;
		this.t.playRandomSound_id = "turtle";
		this.t.layEggs = true;
		this.t.eggStatsID = "egg_turtle";
		this.t.disableJumpAnimation = true;
		this.t.animation_walk = "walk_0,walk_1,walk_2";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_turtle";
		this.t.swampCreature = true;
		this.t.immune_to_slowness = true;
		this.t.swimToIsland = false;
		this.addColorSet("default", "#75B455", "#56823E");
		this.addColorSet("swamp", "#476A72", "#6DA1AD");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.addTrait("slow");
		this.addTrait("weightless");
		this.addTrait("genius");
		this.clone("river_turtle", "turtle");
		this.t.texture_path = "t_river_turtle";
		this.clone("zombie_turtle", "turtle");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_turtle";
		this.setZombie();
		this.clone("crab", "_animal");
		this.t.nameLocale = "Crab";
		this.t.nameTemplate = "crab_name";
		this.t.kingdom = "crab";
		this.t.race = "crab";
		this.t.needFood = true;
		this.t.swimToIsland = false;
		this.t.job = "crab";
		this.t.disableJumpAnimation = true;
		this.t.baseStats.speed = 10f;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S2_Crab;
		this.t.shadowTexture = "unitShadow_2";
		this.t.icon = "iconCrab";
		this.t.color = Toolbox.makeColor("#D7D7D7");
		this.t.baseStats.health = 10;
		this.t.baseStats.damage = 5;
		this.t.texture_path = "t_crab";
		this.t.playRandomSound = false;
		this.t.playRandomSound_id = "crab";
		this.t.layEggs = true;
		this.t.eggStatsID = "egg_crab";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_crab";
		this.addTrait("weightless");
		this.clone("zombie_crab", "crab");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_crab";
		this.setZombie();
		this.clone("fairy", "_peacefulAnimal");
		this.t.nameTemplate = "fairy_name";
		this.t.nameLocale = "Fairy";
		this.t.kingdom = "good";
		this.t.procreate = false;
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_idle = "walk_0,walk_1,walk_2,walk_3";
		this.t.baseStats.health = 10;
		this.t.baseStats.speed = 35f;
		this.t.needFood = false;
		this.t.race = "good";
		this.t.hovering = true;
		this.t.source_meat = false;
		this.t.source_meat_insect = false;
		this.t.actorSize = ActorSize.S3_Rat;
		this.t.shadowTexture = "unitShadow_2";
		this.t.icon = "iconFairy";
		this.t.color = Toolbox.makeColor("#23F3FF");
		this.t.baseStats.damage = 5;
		this.t.texture_path = "t_fairy";
		this.t.disableJumpAnimation = true;
		this.t.have_soul = true;
		this.t.moveFromBlock = true;
		this.t.dieOnBlocks = false;
		this.addTrait("weightless");
		this.addTrait("healing_aura");
		this.addTrait("immune");
		this.addTrait("immortal");
		this.addTrait("energized");
		ActorStats t8 = this.t;
		t8.action_death = (WorldAction)Delegate.Combine(t8.action_death, new WorldAction(ActionLibrary.tryToCreatePlants));
		this.clone("enchanted_fairy", "fairy");
		this.t.action_death = this.get("fairy").action_death;
		this.removeTrait("energized");
		ActorStats actorStats13 = new ActorStats();
		actorStats13.id = "_insect";
		actorStats13.race = "insect";
		actorStats13.kingdom = "neutral_animals";
		actorStats13.canBeKilledByStuff = true;
		actorStats13.canBeKilledByLifeEraser = true;
		actorStats13.damagedByOcean = true;
		actorStats13.procreate = false;
		actorStats13.canBeMovedByPowers = true;
		actorStats13.canBeHurtByPowers = true;
		actorStats13.updateZ = true;
		actorStats13.effectDamage = true;
		actorStats13.flipAnimation = true;
		actorStats13.needFood = false;
		actorStats13.canBeInspected = true;
		actorStats13.hideOnMinimap = true;
		actorStats13.animal = true;
		actorStats13.source_meat_insect = true;
		actorStats13.actorSize = ActorSize.S0_Bug;
		actorStats13.shadowTexture = "unitShadow_2";
		actorStats13.color = Toolbox.makeColor("#23F3FF");
		actorStats13.deathAnimationAngle = true;
		actorStats13.prefab = "p_unit";
		actorStats13.canHaveStatusEffect = true;
		actorStats13.sprite_group_renderer = true;
		pAsset = actorStats13;
		this.t = actorStats13;
		this.add(pAsset);
		this.t.maxAge = 50;
		this.t.animation_idle = "walk_0,walk_1,walk_2";
		this.t.animation_walk = "walk_0,walk_1,walk_2";
		this.t.animation_swim = "swim_0,swim_1,swim_1";
		this.t.baseStats.speed = 3f;
		this.t.baseStats.health = 1;
		this.t.baseStats.damage = 1;
		this.addTrait("peaceful");
		this.t.job = "animal";
		this.t.maxRandomAmount = 5;
		this.clone("_flying_insect", "_insect");
		this.t.animation_idle = "walk_0,walk_1";
		this.t.animation_walk = "walk_0,walk_1";
		this.t.hovering = true;
		this.t.disableJumpAnimation = true;
		this.t.skipSave = true;
		this.t.flipAnimation = false;
		this.t.damagedByOcean = false;
		this.t.moveFromBlock = true;
		this.addTrait("weightless");
		this.clone("bee", "_flying_insect");
		this.t.nameTemplate = "bug_name";
		this.t.nameLocale = "Bee";
		this.t.baseStats.health = 10;
		this.t.baseStats.speed = 15f;
		this.t.hovering_max = 1f;
		this.t.flipAnimation = true;
		this.t.icon = "iconBee";
		this.t.color = Toolbox.makeColor("#23F3FF");
		this.t.baseStats.damage = 5;
		this.t.diet_meat_insect = false;
		this.t.diet_meat = false;
		this.t.diet_meat_same_race = false;
		this.t.texture_path = "t_bee";
		this.t.needFood = false;
		this.t.job = "bee";
		this.clone("fly", "_flying_insect");
		this.t.nameTemplate = "bug_name";
		this.t.nameLocale = "Fly";
		this.t.texture_path = "t_fly";
		this.clone("butterfly", "_flying_insect");
		this.t.nameLocale = "Butterfly";
		this.t.icon = "iconButterfly";
		this.t.baseStats.health = 10;
		this.t.baseStats.speed = 15f;
		this.t.texture_path = "t_butterfly";
		this.t.maxRandomAmount = 6;
		this.t.flipAnimation = true;
		this.t.color = Toolbox.makeColor("#23F3FF");
		ActorStats t9 = this.t;
		t9.action_death = (WorldAction)Delegate.Combine(t9.action_death, new WorldAction(ActionLibrary.tryToCreatePlants));
		this.clone("grasshopper", "_insect");
		this.t.nameTemplate = "bug_name";
		this.t.nameLocale = "Grasshopper";
		this.t.texture_path = "t_grasshopper";
		this.t.shadow = false;
		this.clone("beetle", "_insect");
		this.t.nameTemplate = "bug_name";
		this.t.nameLocale = "Beetle";
		this.t.disableJumpAnimation = true;
		this.t.texture_path = "t_beetle";
		this.t.shadow = false;
		ActorStats actorStats14 = new ActorStats();
		actorStats14.id = "_egg";
		actorStats14.kingdom = "neutral_animals";
		actorStats14.egg = true;
		actorStats14.source_meat = true;
		actorStats14.canBeKilledByStuff = true;
		actorStats14.canBeKilledByLifeEraser = true;
		actorStats14.skipFightLogic = true;
		actorStats14.updateZ = true;
		actorStats14.effectDamage = true;
		actorStats14.canBeMovedByPowers = true;
		actorStats14.canBeHurtByPowers = true;
		actorStats14.specialAnimation = true;
		actorStats14.hideOnMinimap = true;
		actorStats14.canBeInspected = true;
		actorStats14.deathAnimationAngle = true;
		actorStats14.prefab = "p_unit";
		actorStats14.ignoreJobs = true;
		actorStats14.canHaveStatusEffect = true;
		actorStats14.sprite_group_renderer = true;
		pAsset = actorStats14;
		this.t = actorStats14;
		this.add(pAsset);
		this.t.color = Toolbox.makeColor("#E5E5B8");
		this.t.needFood = false;
		this.t.actorSize = ActorSize.S1_Egg;
		this.t.shadowTexture = "unitShadow_2";
		this.t.animation_walk = "walk_0";
		this.t.kingdom = "neutral_animals";
		this.addFlag("egg");
		this.t.setBaseStats(1, 0, 0, 0, 0, 0, 0);
		this.t.inspect_stats = false;
		this.addTrait("strong_minded");
		this.addTrait("immune");
		this.clone("egg_chicken", "_egg");
		this.t.nameLocale = "Chicken";
		this.t.race = "chicken";
		this.t.nameTemplate = "chicken_name";
		this.t.growIntoID = "chick";
		this.t.texture_path = "t_egg_chicken";
		this.clone("egg_crab", "_egg");
		this.t.nameLocale = "Crab";
		this.t.nameTemplate = "crab_name";
		this.t.race = "crab";
		this.t.growIntoID = "crab";
		this.t.texture_path = "t_egg_crab";
		this.clone("egg_turtle", "_egg");
		this.t.nameLocale = "Turtle";
		this.t.nameTemplate = "turtle_name";
		this.t.race = "turtle";
		this.t.growIntoID = "turtle";
		this.t.texture_path = "t_egg_turtle";
		this.clone("chicken", "_herbivore");
		this.t.nameLocale = "Chicken";
		this.t.baseStats.health = 50;
		this.t.baseStats.speed = 20f;
		this.t.baseStats.damage = 4;
		this.t.race = "chicken";
		this.t.nameTemplate = "chicken_name";
		this.t.diet_grass = true;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S6_Chicken;
		this.t.shadowTexture = "unitShadow_3";
		this.t.layEggs = true;
		this.t.eggStatsID = "egg_chicken";
		this.t.icon = "iconChicken";
		this.t.color = Toolbox.makeColor("#DEDAC4");
		this.t.texture_path = "t_chicken";
		this.addTrait("weightless");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_chicken";
		this.addColorSet("default", "#BFBFBF", "#FFFFFF");
		this.addColorSet("default", "#A37459", "#2D2D2D");
		this.addColorSet("default", "#DB9641", "#C7883A");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.clone("rooster", "chicken");
		this.t.texture_path = "t_rooster";
		this.t.baseStats.health = 80;
		this.t.baseStats.damage = 6;
		this.t.layEggs = false;
		this.addColorSet("default_white-orange", "#FAFCFB", "#C66B22");
		this.clone("zombie_chicken", "chicken");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_chicken";
		this.setZombie();
		this.clone("chick", "chicken");
		this.t.procreate = false;
		this.t.nameTemplate = "chicken_name";
		this.t.baseStats.health = 20;
		this.t.baseStats.speed = 10f;
		this.t.baseStats.damage = 1;
		this.t.layEggs = false;
		this.t.texture_path = "t_chick";
		this.t.baby = true;
		this.t.timeToGrow = 100;
		this.t.growIntoID = "chicken";
		this.t.actorSize = ActorSize.S3_Rat;
		this.t.shadowTexture = "unitShadow_2";
		this.clone("rat", "_omnivore");
		this.t.nameLocale = "Rat";
		this.t.nameTemplate = "rat_name";
		this.t.baseStats.health = 10;
		this.t.baseStats.damage = 2;
		this.t.actorSize = ActorSize.S3_Rat;
		this.t.shadowTexture = "unitShadow_2";
		this.t.texture_path = "t_rat";
		this.t.damagedByOcean = false;
		this.t.race = "rat";
		this.t.kingdom = "rats";
		this.t.baseStats.speed = 30f;
		this.t.shadow = true;
		this.t.needFood = true;
		this.t.source_meat = true;
		this.t.diet_meat_same_race = true;
		this.t.maxRandomAmount = 5;
		this.t.canAttackBuildings = false;
		this.t.color = Toolbox.makeColor("#2D2D2D");
		this.t.job = "rat";
		this.addTrait("rat");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_rat";
		this.clone("zombie_rat", "rat");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_rat";
		this.setZombie();
		this.clone("ratKing", "_omnivore");
		this.t.nameLocale = "Rat King";
		this.t.procreate = false;
		this.t.nameTemplate = "rat_name";
		this.t.baseStats.health = 50;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.damage = 5;
		this.t.race = "rat";
		this.t.kingdom = "ratKings";
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S3_Rat;
		this.t.shadowTexture = "unitShadow_2";
		this.t.icon = "iconRatKing";
		this.t.color = Toolbox.makeColor("#2D2D2D");
		this.t.texture_path = "t_ratKing";
		this.t.needFood = true;
		this.t.diet_meat = true;
		this.t.canAttackBuildings = false;
		this.t.diet_meat_same_race = true;
		this.t.job = "rat";
		this.addTrait("weightless");
		this.addTrait("ratKing");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_ratKing";
		this.clone("zombie_ratKing", "ratKing");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_ratKing";
		this.setZombie();
		this.clone("cat", "_carnivore");
		this.t.nameLocale = "Cat";
		this.t.nameTemplate = "cat_name";
		this.t.kingdom = "cats";
		this.t.baseStats.health = 99;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.damage = 4;
		this.t.race = "cat";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S7_Cat;
		this.t.shadowTexture = "unitShadow_3";
		this.t.icon = "iconCat";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_cat";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_cat";
		this.addTrait("weightless");
		this.t.defaultAttack = "claws";
		this.addColorSet("polar", "#BFBFBF", "#FFFFFF");
		this.addColorSet("jungle", "#494949", "#2D2D2D");
		this.addColorSet("savanna", "#E29B44", "#C7883A");
		this.addColorSet("default_brown-bright-dark", "#FCC291", "#BC712B");
		this.addColorSet("default_blue-bright-dark", "#A7A5C6", "#8B89A6");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.clone("zombie_cat", "cat");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_cat";
		this.setZombie();
		this.clone("rabbit", "_herbivore");
		this.t.nameLocale = "Rabbit";
		this.t.baseStats.health = 15;
		this.t.baseStats.speed = 20f;
		this.t.nameTemplate = "rabbit_name";
		this.t.race = "rabbit";
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S6_Chicken;
		this.t.shadowTexture = "unitShadow_2";
		this.t.icon = "iconRabbit";
		this.t.color = Toolbox.makeColor("#D3D6D1");
		this.t.texture_path = "t_rabbit";
		this.addTrait("weightless");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_rabbit";
		this.addColorSet("default", "#D3D6D1", "#695049");
		this.addColorSet("polar", "#BFBFBF", "#FFFFFF");
		this.addColorSet("savanna", "#E9D2B0", "#D8B27D");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.addTrait("fast");
		this.clone("zombie_rabbit", "rabbit");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_rabbit";
		this.setZombie();
		this.clone("piranha", "_mob");
		this.t.nameLocale = "Piranha";
		this.t.race = "piranha";
		this.t.kingdom = "piranhas";
		this.t.nameTemplate = "piranha_name";
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 200f;
		this.t.baseStats.damage = 20;
		this.t.baseStats.knockback = 0.5f;
		this.t.canAttackBuildings = false;
		this.t.dieOnGround = true;
		this.t.swimToIsland = false;
		this.t.diet_meat = true;
		this.t.actorSize = ActorSize.S4_Piranha;
		this.t.icon = "iconPiranha";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#3483B6");
		this.t.job = "random_swim";
		this.t.texture_path = "t_piranha";
		this.t.immune_to_slowness = true;
		this.addColorSet("default", "#64787D", "#4E4860");
		this.addColorSet("swamp", "#647D66", "#485D60");
		this.t.landCreature = false;
		this.t.oceanCreature = true;
		this.t.swampCreature = true;
		this.clone("bandit", "_mob");
		this.t.nameLocale = "Bandits";
		this.t.body_separate_part_head = true;
		this.t.body_separate_part_hands = true;
		this.t.race = "bandit";
		this.t.kingdom = "bandits";
		this.t.baseStats.speed = 60f;
		this.t.baseStats.attackSpeed = 100f;
		this.t.baseStats.damage = 10;
		this.t.baseStats.knockback = 1f;
		this.t.icon = "iconBandit";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#4A3F35");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie";
		this.t.skeletonID = "skeleton_cursed";
		this.t.texture_path = "t_bandit";
		this.t.texture_heads = "t_bandit_heads";
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"spear",
			"sword",
			"bow"
		});
		this.t.defaultWeaponsMaterial = List.Of<string>(new string[]
		{
			"bronze",
			"steel",
			"iron"
		});
		this.t.use_items = true;
		this.t.take_items = true;
		this.t.have_soul = true;
		this.addTrait("bomberman");
		this.t.disableJumpAnimation = true;
		this.clone("snowman", "_mob");
		this.t.nameLocale = "Snowman";
		this.t.race = "snowman";
		this.t.kingdom = "snowman";
		this.t.nameTemplate = "snowman_name";
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 70f;
		this.t.baseStats.damage = 10;
		this.t.baseStats.knockback = 1f;
		this.t.defaultAttack = "snowball";
		this.t.icon = "iconSnowman";
		this.t.color = Toolbox.makeColor("#FFFFFF");
		this.t.texture_path = "t_snowman";
		this.t.damagedByOcean = true;
		this.t.damagedByRain = true;
		this.t.canTurnIntoMush = false;
		this.t.canTurnIntoTumorMonster = false;
		this.addTrait("regeneration");
		this.addTrait("cold_aura");
		this.addTrait("fat");
		this.addTrait("freeze_proof");
		this.t.disableJumpAnimation = true;
		this.clone("alien", "_mob");
		this.t.texture_path = "t_alien";
		this.t.texture_heads = "t_alien_heads";
		this.t.body_separate_part_head = true;
		this.t.body_separate_part_hands = true;
		this.t.nameLocale = "Alien";
		this.t.race = "alien";
		this.t.kingdom = "aliens";
		this.t.baseStats.health = 600;
		this.t.baseStats.speed = 20f;
		this.t.baseStats.attackSpeed = 70f;
		this.t.baseStats.damage = 10;
		this.t.baseStats.knockback = 1f;
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"alien_blaster"
		});
		this.t.icon = "iconAlien";
		this.t.color = Toolbox.makeColor("#00FF00");
		this.t.use_items = true;
		this.t.canTurnIntoTumorMonster = true;
		this.t.canTurnIntoMush = true;
		this.t.mushID = "mush_unit";
		this.t.tumorMonsterID = "tumor_monster_unit";
		this.t.nameTemplate = "alien_name";
		this.t.have_soul = true;
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.addTrait("fat");
		this.addTrait("acid_blood");
		this.addTrait("acid_proof");
		this.t.disableJumpAnimation = true;
		this.clone("bear", "_carnivore");
		this.t.nameLocale = "Bear";
		this.t.race = "bear";
		this.t.kingdom = "bears";
		this.t.nameTemplate = "bear_name";
		this.t.baseStats.health = 150;
		this.t.baseStats.speed = 50f;
		this.t.baseStats.attackSpeed = 50f;
		this.t.baseStats.damage = 25;
		this.t.baseStats.knockback = 1.2f;
		this.t.baseStats.knockbackReduction = 30f;
		this.t.baseStats.targets = 2;
		this.t.procreate = true;
		this.t.diet_meat = true;
		this.t.diet_berries = true;
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_bear";
		this.t.canAttackBuildings = false;
		this.t.actorSize = ActorSize.S15_Bear;
		this.t.shadowTexture = "unitShadow_6";
		this.t.icon = "iconBear";
		this.t.color = Toolbox.makeColor("#6C522D");
		this.t.texture_path = "t_bear";
		this.addTrait("strong");
		this.t.defaultAttack = "claws";
		this.addColorSet("polar", "#BFBFBF", "#FFFFFF");
		this.addColorSet("default", "#A37459", "#2D2D2D");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.clone("zombie_bear", "bear");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_bear";
		this.setZombie();
		this.clone("wolf", "_carnivore");
		this.t.nameLocale = "Wolfs";
		this.t.nameTemplate = "wolf_name";
		this.t.race = "wolf";
		this.t.kingdom = "wolves";
		this.t.baseStats.speed = 75f;
		this.t.canAttackBuildings = false;
		this.t.baseStats.attackSpeed = 100f;
		this.t.baseStats.damage = 15;
		this.t.baseStats.knockback = 0.8f;
		this.t.procreate = true;
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_wolf";
		this.t.actorSize = ActorSize.S12_Wolf;
		this.t.shadowTexture = "unitShadow_7";
		this.t.texture_path = "t_wolf";
		this.t.icon = "iconWolf";
		this.t.color = Toolbox.makeColor("#393939");
		this.t.job = "animal_herd";
		this.t.playRandomSound = true;
		this.t.playRandomSound_id = "wolf";
		this.t.diet_meat_same_race = true;
		this.t.diet_meat = true;
		this.addColorSet("polar", "#BFBFBF", "#FFFFFF");
		this.addColorSet("default", "#A37459", "#825D45");
		this.addColorSet("default", "#9B9B9B", "#7C7C7C");
		this.addColorSet("default_dark", "#919191", "#493838");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.clone("dog", "_peacefulAnimal");
		this.t.nameLocale = "Dog";
		this.t.kingdom = "neutral_animals";
		this.t.nameTemplate = "wolf_name";
		this.t.baseStats.health = 150;
		this.t.baseStats.speed = 60f;
		this.t.baseStats.damage = 10;
		this.t.race = "dog";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S10_Dog;
		this.t.shadowTexture = "unitShadow_5";
		this.t.icon = "iconDog";
		this.t.color = Toolbox.makeColor("#393939");
		this.t.texture_path = "t_dog";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_dog";
		this.t.defaultAttack = "jaws";
		this.addColorSet("default_white-dark", "#919191", "#493838");
		this.addColorSet("default_brown-bright-dark", "#AA683B", "#8E3D07");
		this.addColorSet("polar", "#BFBFBF", "#FFFFFF");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.t.clearTraits();
		this.addTrait("fast");
		this.clone("zombie_dog", "dog");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_dog";
		this.addTrait("eyepatch");
		this.setZombie();
		this.clone("snake", "_carnivore");
		this.t.nameLocale = "Snake";
		this.t.kingdom = "snakes";
		this.t.nameTemplate = "snake_name";
		this.t.baseStats.health = 40;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.damage = 4;
		this.t.race = "snake";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S5_Snake;
		this.t.shadowTexture = "unitShadow_4";
		this.t.icon = "iconSnake";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_snake";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_snake";
		this.t.immune_to_slowness = true;
		this.t.swampCreature = true;
		this.addColorSet("default", "#9B7C52", "#61E742");
		this.addColorSet("jungle", "#D6E742", "#61E742");
		this.addColorSet("savanna", "#EA6042", "#D6E742");
		this.addColorSet("swamp_blue", "#61E742", "#9542EA");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.addTrait("poison_immune");
		this.addTrait("venomous");
		this.addTrait("weightless");
		this.t.defaultAttack = "venomous_bite";
		this.clone("zombie_snake", "snake");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_snake";
		this.setZombie();
		this.clone("frog", "_peacefulAnimal");
		this.t.nameLocale = "Frog";
		this.t.nameTemplate = "frog_name";
		this.t.baseStats.health = 20;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.damage = 5;
		this.t.race = "frog";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.diet_meat_insect = true;
		this.t.actorSize = ActorSize.S2_Crab;
		this.t.shadowTexture = "unitShadow_3";
		this.t.icon = "iconFrog";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_frog";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_frog";
		this.t.immune_to_slowness = true;
		this.t.swampCreature = true;
		this.t.swimToIsland = false;
		this.t.clearTraits();
		this.addTrait("poisonous");
		this.addTrait("weightless");
		this.addColorSet("default_green", "#8AD441", "#12B013");
		this.addColorSet("jungle_red_yellow", "#CB431F", "#85CB1F");
		this.addColorSet("savanna", "#7F3710", "#C59C16");
		this.addColorSet("mushroom", "#C902A1", "#FFDB2B");
		this.addColorSet("corrupted", "#111111", "#333333");
		this.clone("zombie_frog", "frog");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_frog";
		this.setZombie();
		this.clone("rhino", "_herbivore");
		this.t.nameLocale = "Rhino";
		this.t.kingdom = "rhinos";
		this.t.nameTemplate = "rhino_name";
		this.t.baseStats.health = 250;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.armor = 10;
		this.t.baseStats.attackSpeed = 20f;
		this.t.baseStats.damage = 18;
		this.t.baseStats.knockback = 1.2f;
		this.t.baseStats.knockbackReduction = 30f;
		this.t.baseStats.targets = 3;
		this.t.race = "rhino";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S16_Buffalo;
		this.t.shadowTexture = "unitShadow_11";
		this.t.icon = "iconRhino";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_rhino";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_rhino";
		this.t.maxRandomAmount = 1;
		this.t.procreate_age = 6;
		this.t.animal_baby_making_around_limit = 4;
		this.t.clearTraits();
		this.addTrait("strong");
		this.addTrait("fat");
		this.clone("zombie_rhino", "rhino");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_rhino";
		this.setZombie();
		this.clone("monkey", "_herbivore");
		this.t.nameLocale = "Monkey";
		this.t.kingdom = "neutral_animals";
		this.t.nameTemplate = "monkey_name";
		this.t.baseStats.health = 70;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.damage = 15;
		this.t.baseStats.attackSpeed = 50f;
		this.t.baseStats.knockback = 1f;
		this.t.race = "monkey";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S9_Monkey;
		this.t.shadowTexture = "unitShadow_3";
		this.t.icon = "iconMonkey";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_monkey";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_monkey";
		this.t.clearTraits();
		this.addTrait("genius");
		this.addTrait("agile");
		this.t.defaultAttack = "rocks";
		this.clone("zombie_monkey", "monkey");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_monkey";
		this.t.defaultAttack = "jaws";
		this.setZombie();
		this.clone("crocodile", "_carnivore");
		this.t.nameLocale = "Crocodile";
		this.t.kingdom = "crocodiles";
		this.t.nameTemplate = "crocodile_name";
		this.t.baseStats.health = 200;
		this.t.baseStats.speed = 20f;
		this.t.baseStats.armor = 10;
		this.t.baseStats.damage = 30;
		this.t.baseStats.knockbackReduction = 80f;
		this.t.swimToIsland = false;
		this.t.race = "crocodile";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S15_Bear;
		this.t.shadowTexture = "unitShadow_21";
		this.t.icon = "iconCrocodile";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_crocodile";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_crocodile";
		this.t.immune_to_slowness = true;
		this.t.maxRandomAmount = 2;
		this.t.landCreature = true;
		this.t.oceanCreature = true;
		this.t.swampCreature = true;
		this.addTrait("tough");
		this.clone("zombie_crocodile", "crocodile");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_crocodile";
		this.setZombie();
		this.clone("hyena", "_carnivore");
		this.t.nameLocale = "Hyena";
		this.t.kingdom = "hyenas";
		this.t.nameTemplate = "hyena_name";
		this.t.baseStats.health = 75;
		this.t.baseStats.speed = 60f;
		this.t.baseStats.damage = 7;
		this.t.race = "hyena";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S10_Dog;
		this.t.shadowTexture = "unitShadow_5";
		this.t.icon = "iconHyena";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_hyena";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_hyena";
		this.t.maxRandomAmount = 2;
		this.clone("zombie_hyena", "hyena");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_hyena";
		this.setZombie();
		this.clone("buffalo", "_herbivore");
		this.t.nameLocale = "Buffalo";
		this.t.nameTemplate = "buffalo_name";
		this.t.kingdom = "neutral_animals";
		this.t.baseStats.health = 200;
		this.t.baseStats.speed = 50f;
		this.t.baseStats.damage = 15;
		this.t.race = "buffalo";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S16_Buffalo;
		this.t.shadowTexture = "unitShadow_7";
		this.t.icon = "iconBuffalo";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_buffalo";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_buffalo";
		this.t.maxRandomAmount = 3;
		this.t.clearTraits();
		this.addTrait("strong");
		this.clone("zombie_buffalo", "buffalo");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_buffalo";
		this.setZombie();
		this.clone("fox", "_carnivore");
		this.t.nameLocale = "Fox";
		this.t.nameTemplate = "fox_name";
		this.t.kingdom = "neutral_animals";
		this.t.baseStats.speed = 50f;
		this.t.baseStats.damage = 10;
		this.t.race = "fox";
		this.t.skipFightLogic = false;
		this.t.source_meat = true;
		this.t.actorSize = ActorSize.S8_Fox;
		this.t.shadowTexture = "unitShadow_4";
		this.t.icon = "iconFox";
		this.t.color = Toolbox.makeColor("#C2974E");
		this.t.texture_path = "t_fox";
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie_fox";
		this.t.clearTraits();
		this.addTrait("genius");
		this.addTrait("fast");
		this.clone("zombie_fox", "fox");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_fox";
		this.setZombie();
		this.clone("zombie_wolf", "wolf");
		this.t.nameLocale = "Zombie";
		this.t.texture_path = "t_zombie_wolf";
		this.setZombie();
		this.clone("demon", "_mob");
		this.t.nameLocale = "Demon";
		this.t.nameTemplate = "demon_name";
		this.t.body_separate_part_head = true;
		this.t.body_separate_part_hands = true;
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"flame_sword"
		});
		this.t.use_items = true;
		this.t.race = "demon";
		this.t.kingdom = "demons";
		this.t.baseStats.health = 666;
		this.t.baseStats.speed = 20f;
		this.t.baseStats.attackSpeed = 1f;
		this.t.baseStats.damage = 10;
		this.t.baseStats.knockback = 1f;
		this.t.baseStats.targets = 0;
		this.t.damagedByOcean = true;
		this.t.damagedByRain = true;
		this.t.dieInLava = false;
		this.t.icon = "iconDemon";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#EE3A42");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie";
		this.t.skeletonID = "skeleton_cursed";
		this.t.job = "move_mob";
		this.t.texture_path = "t_demon";
		this.t.texture_heads = "t_demon_heads";
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.disableJumpAnimation = true;
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.addTrait("burning_feet");
		this.addTrait("fire_blood");
		this.addTrait("fire_proof");
		this.addTrait("evil");
		this.clone("fire_skull", "_mob");
		this.t.nameLocale = "Fire Skull";
		this.t.nameTemplate = "fire_skull_name";
		this.t.canTurnIntoMush = false;
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = false;
		this.t.have_skin = false;
		this.t.race = "demon";
		this.t.kingdom = "demons";
		this.t.baseStats.health = 200;
		this.t.baseStats.speed = 20f;
		this.t.baseStats.attackSpeed = 40f;
		this.t.baseStats.damage = 8;
		this.t.icon = "iconFireSkull";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#EE3A42");
		this.t.job = "move_mob";
		this.t.texture_path = "t_fire_skull";
		this.t.disableJumpAnimation = true;
		this.t.animation_idle = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.maxRandomAmount = 4;
		this.addTrait("immortal");
		this.addTrait("evil");
		this.addTrait("weightless");
		this.addTrait("fire_blood");
		this.addTrait("fire_proof");
		this.clone("acid_blob", "_mob");
		this.t.nameLocale = "Acid Blob";
		this.t.nameTemplate = "acid_blob_name";
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = false;
		this.t.have_skin = false;
		this.t.canTurnIntoMush = false;
		this.t.race = "acids";
		this.t.kingdom = "acids";
		this.t.baseStats.health = 200;
		this.t.baseStats.speed = 10f;
		this.t.baseStats.crit = 20f;
		this.t.baseStats.attackSpeed = 40f;
		this.t.baseStats.damage = 15;
		this.t.icon = "iconAcidBlob";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#008800");
		this.t.job = "move_mob";
		this.t.texture_path = "t_acid_blob";
		this.t.disableJumpAnimation = true;
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.maxRandomAmount = 2;
		this.addTrait("acid_blood");
		this.addTrait("acid_proof");
		this.addTrait("acid_touch");
		this.addTrait("fat");
		this.clone("zombie", "_mob");
		this.t.nameLocale = "Zombie";
		this.t.body_separate_part_head = true;
		this.t.body_separate_part_hands = true;
		this.t.baseStats.health = 150;
		this.t.baseStats.speed = 10f;
		this.t.baseStats.attackSpeed = 110f;
		this.t.baseStats.damage = 24;
		this.t.baseStats.dodge = 0f;
		this.t.baseStats.knockback = 1f;
		this.t.icon = "iconZombie";
		this.t.needFood = false;
		this.t.use_items = true;
		this.t.color = Toolbox.makeColor("#24803E");
		this.t.job = "move_mob";
		this.t.texture_path = "t_zombie_human";
		this.t.texture_heads = "t_zombie_human_heads";
		this.t.canAttackBuildings = false;
		this.t.canAttackBrains = true;
		this.t.disableJumpAnimation = true;
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.setZombie();
		this.clone("zombie_orc", "zombie");
		this.t.texture_path = "t_zombie_orc";
		this.t.texture_heads = "t_zombie_orc_heads";
		this.addTrait("regeneration");
		this.addTrait("savage");
		this.clone("zombie_dwarf", "zombie");
		this.t.texture_path = "t_zombie_dwarf";
		this.t.texture_heads = "t_zombie_dwarf_heads";
		this.addTrait("miner");
		this.clone("zombie_elf", "zombie");
		this.t.texture_path = "t_zombie_elf";
		this.t.texture_heads = "t_zombie_elf_heads";
		this.addTrait("weightless");
		this.clone("necromancer", "_mob");
		this.t.nameLocale = "Necromancer";
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = true;
		this.t.race = "necromancer";
		this.t.kingdom = "undead";
		this.t.baseStats.health = 500;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 0f;
		this.t.baseStats.damage = 1;
		this.t.baseStats.knockback = 1f;
		this.t.baseStats.targets = 1;
		this.t.dieInLava = true;
		this.t.icon = "iconNecromancer";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#EE3A42");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie";
		this.t.skeletonID = "skeleton_cursed";
		this.t.job = "necromancer";
		this.t.attack_spells = List.Of<string>(new string[]
		{
			"curse",
			"spawnSkeleton",
			"bloodRain",
			"bloodRain"
		});
		this.t.effect_cast_top = "fx_cast_top_green";
		this.t.effect_cast_ground = "fx_cast_ground_green";
		this.t.texture_path = "t_necromancer";
		this.t.use_items = true;
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"necromancer_staff"
		});
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.disableJumpAnimation = true;
		ActorStats t10 = this.t;
		t10.action_death = (WorldAction)Delegate.Combine(t10.action_death, new WorldAction(ActionLibrary.mageDeath));
		this.t.have_soul = true;
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.addTrait("evil");
		this.clone("druid", "_mob");
		this.t.nameLocale = "Druid";
		this.t.body_separate_part_head = true;
		this.t.body_separate_part_hands = true;
		this.t.race = "good";
		this.t.kingdom = "druid";
		this.t.baseStats.health = 500;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 0f;
		this.t.baseStats.damage = 1;
		this.t.baseStats.knockback = 1f;
		this.t.baseStats.targets = 1;
		this.t.dieInLava = true;
		this.t.icon = "iconDruid";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#4CDB75");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie";
		this.t.skeletonID = "skeleton_cursed";
		this.t.job = "druid";
		this.t.attack_spells = List.Of<string>(new string[]
		{
			"bloodRain"
		});
		this.t.effect_cast_top = "fx_cast_top_blue";
		this.t.effect_cast_ground = "fx_cast_ground_blue";
		this.t.texture_path = "t_druid";
		this.t.texture_heads = "t_druid_heads";
		this.t.use_items = true;
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"druid_staff"
		});
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.disableJumpAnimation = true;
		ActorStats t11 = this.t;
		t11.action_death = (WorldAction)Delegate.Combine(t11.action_death, new WorldAction(ActionLibrary.mageDeath));
		ActorStats t12 = this.t;
		t12.action_death = (WorldAction)Delegate.Combine(t12.action_death, new WorldAction(ActionLibrary.tryToCreatePlants));
		ActorStats t13 = this.t;
		t13.action_death = (WorldAction)Delegate.Combine(t13.action_death, new WorldAction(ActionLibrary.tryToGrowTree));
		this.t.have_soul = true;
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.addTrait("flower_prints");
		this.clone("plagueDoctor", "_mob");
		this.t.nameLocale = "Plague Doctor";
		this.t.immune_to_tumor = true;
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = true;
		this.t.race = "good";
		this.t.kingdom = "good";
		this.t.maxAge = 100;
		this.t.baseStats.health = 500;
		this.t.baseStats.speed = 20f;
		this.t.baseStats.attackSpeed = 0f;
		this.t.baseStats.damage = 1;
		this.t.baseStats.knockback = 1f;
		this.t.baseStats.targets = 1;
		this.t.dieInLava = true;
		this.t.icon = "iconPlagueDoctor";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#EE3A42");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie";
		this.t.skeletonID = "skeleton_cursed";
		this.t.job = "plague_doctor";
		this.t.attack_spells = List.Of<string>(new string[]
		{
			"bloodRain"
		});
		this.t.effect_cast_top = "fx_cast_top_blue";
		this.t.effect_cast_ground = "fx_cast_ground_blue";
		this.t.texture_path = "t_plagueDoctor";
		this.t.use_items = true;
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"plague_doctor_staff"
		});
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.disableJumpAnimation = true;
		ActorStats t14 = this.t;
		t14.action_death = (WorldAction)Delegate.Combine(t14.action_death, new WorldAction(ActionLibrary.mageDeath));
		this.t.have_soul = true;
		this.addTrait("regeneration");
		this.addTrait("immune");
		this.addTrait("fire_proof");
		this.clone("whiteMage", "_mob");
		this.t.nameLocale = "White Mage";
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = true;
		this.t.race = "good";
		this.t.kingdom = "good";
		this.t.baseStats.health = 300;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 0f;
		this.t.baseStats.damage = 1;
		this.t.baseStats.knockback = 1f;
		this.t.baseStats.targets = 1;
		this.t.dieInLava = true;
		this.t.icon = "iconWhiteMage";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#EE3A42");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie";
		this.t.skeletonID = "skeleton_cursed";
		this.t.job = "white_mage";
		this.t.attack_spells = List.Of<string>(new string[]
		{
			"teleportRandom",
			"bloodRain",
			"shield"
		});
		this.t.texture_path = "t_whitemage";
		this.t.effect_teleport = "fx_teleport_blue";
		this.t.effect_cast_top = "fx_cast_top_blue";
		this.t.effect_cast_ground = "fx_cast_ground_blue";
		this.t.use_items = true;
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"white_staff"
		});
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.disableJumpAnimation = true;
		ActorStats t15 = this.t;
		t15.action_death = (WorldAction)Delegate.Combine(t15.action_death, new WorldAction(ActionLibrary.mageDeath));
		this.t.have_soul = true;
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.addTrait("freeze_proof");
		this.clone("evilMage", "_mob");
		this.t.nameLocale = "Evil Mage";
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = true;
		this.t.race = "evilMage";
		this.t.nameTemplate = "evil_mage_name";
		this.t.kingdom = "evil";
		this.t.baseStats.health = 500;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 0f;
		this.t.baseStats.damage = 1;
		this.t.baseStats.knockback = 1f;
		this.t.baseStats.targets = 1;
		this.t.dieInLava = true;
		this.t.icon = "iconEvilMage";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#EE3A42");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie";
		this.t.skeletonID = "skeleton_cursed";
		this.t.job = "evil_mage";
		this.t.effect_teleport = "fx_teleport_red";
		this.t.effect_cast_top = "fx_cast_top_red";
		this.t.effect_cast_ground = "fx_cast_ground_red";
		this.t.attack_spells = List.Of<string>(new string[]
		{
			"teleportRandom",
			"lightning",
			"tornado",
			"bloodRain",
			"bloodRain",
			"fire"
		});
		this.t.texture_path = "t_evilmage";
		this.t.use_items = true;
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"evil_staff"
		});
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.disableJumpAnimation = true;
		ActorStats t16 = this.t;
		t16.action_death = (WorldAction)Delegate.Combine(t16.action_death, new WorldAction(ActionLibrary.mageDeath));
		this.t.have_soul = true;
		this.addTrait("evil");
		this.addTrait("fire_proof");
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.clone("skeleton", "_mob");
		this.t.nameLocale = "Skeleton";
		this.t.body_separate_part_head = true;
		this.t.body_separate_part_hands = true;
		this.t.nameTemplate = "skeleton_name";
		this.t.have_skin = false;
		this.t.race = "undead";
		this.t.kingdom = "undead";
		this.t.baseStats.health = 60;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 40f;
		this.t.baseStats.damage = 10;
		this.t.icon = "iconSkeleton";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#ffffff");
		this.t.job = "skeleton_job";
		this.t.texture_path = "t_skeleton";
		this.t.texture_heads = "t_skeleton_heads";
		this.t.defaultWeapons = List.Of<string>(new string[]
		{
			"spear",
			"sword",
			"bow"
		});
		this.t.defaultWeaponsMaterial = List.Of<string>(new string[]
		{
			"bronze",
			"steel",
			"iron"
		});
		this.t.use_items = true;
		this.t.take_items = true;
		this.t.disableJumpAnimation = true;
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.canTurnIntoMush = false;
		this.t.canTurnIntoTumorMonster = false;
		this.addTrait("immortal");
		this.addTrait("weightless");
		this.clone("jumpy_skull", "_mob");
		this.t.nameLocale = "Jumpy Skull";
		this.t.nameTemplate = "jumpy_skull_name";
		this.t.canTurnIntoMush = false;
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = false;
		this.t.have_skin = false;
		this.t.race = "undead";
		this.t.kingdom = "undead";
		this.t.baseStats.health = 100;
		this.t.baseStats.speed = 8f;
		this.t.baseStats.attackSpeed = 40f;
		this.t.baseStats.damage = 6;
		this.t.icon = "iconJumpySkull";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#ffffff");
		this.t.job = "move_mob";
		this.t.texture_path = "t_jumpy_skull";
		this.t.disableJumpAnimation = true;
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.maxRandomAmount = 4;
		this.addTrait("immortal");
		this.addTrait("weightless");
		this.clone("ghost", "_mob");
		this.t.nameLocale = "Ghost";
		this.t.body_separate_part_head = false;
		this.t.body_separate_part_hands = false;
		this.t.have_skin = false;
		this.t.canTurnIntoZombie = false;
		this.t.race = "undead";
		this.t.kingdom = "undead";
		this.t.baseStats.health = 333;
		this.t.baseStats.speed = 10f;
		this.t.baseStats.armor = 77;
		this.t.baseStats.attackSpeed = 13f;
		this.t.baseStats.damage = 13;
		this.t.icon = "iconGhost";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#ffffff");
		this.t.job = "skeleton_job";
		this.t.texture_path = "t_ghost";
		this.t.disableJumpAnimation = true;
		this.t.animation_idle = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.maxRandomAmount = 1;
		this.t.canTurnIntoMush = false;
		this.t.mushID = string.Empty;
		this.t.canTurnIntoTumorMonster = false;
		this.t.tumorMonsterID = string.Empty;
		this.t.have_skin = false;
		this.t.immune_to_injuries = true;
		this.t.dieOnBlocks = false;
		this.addTrait("immortal");
		this.addTrait("weightless");
		this.addTrait("cursed");
		this.addTrait("fire_proof");
		this.addTrait("freeze_proof");
		this.clone("skeleton_cursed", "skeleton");
		this.t.defaultWeapons.Clear();
		this.t.defaultWeaponsMaterial.Clear();
		this.clone("mush_unit", "_mob");
		this.t.nameLocale = "Mush";
		this.t.body_separate_part_head = true;
		this.t.body_separate_part_hands = true;
		this.t.race = "mush";
		this.t.kingdom = "mush";
		this.t.baseStats.health = 300;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 40f;
		this.t.baseStats.damage = 30;
		this.t.icon = "iconMush";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#FF49CB");
		this.t.job = "mush";
		this.t.texture_path = "t_mush_unit";
		this.t.texture_heads = "t_mush_unit_heads";
		this.t.use_items = true;
		this.t.take_items = true;
		this.t.disableJumpAnimation = true;
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.canTurnIntoZombie = false;
		this.t.canTurnIntoMush = false;
		this.t.canTurnIntoTumorMonster = false;
		this.addTrait("immortal");
		this.addTrait("weightless");
		this.addTrait("mushSpores");
		this.addTrait("regeneration");
		this.clone("mush_animal", "mush_unit");
		this.t.baseStats.health = 150;
		this.t.baseStats.speed = 20f;
		this.t.baseStats.attackSpeed = 20f;
		this.t.baseStats.damage = 20;
		this.t.texture_path = "t_mush_animal";
		this.t.body_separate_part_hands = false;
		this.t.body_separate_part_head = false;
		this.t.use_items = false;
		this.t.take_items = false;
		this.clone("tumor_monster_unit", "_mob");
		this.t.nameLocale = "Tumor";
		this.t.immune_to_tumor = true;
		this.t.canTurnIntoTumorMonster = false;
		this.t.body_separate_part_head = true;
		this.t.body_separate_part_hands = true;
		this.t.race = "tumor";
		this.t.kingdom = "tumor";
		this.t.baseStats.health = 60;
		this.t.baseStats.speed = 30f;
		this.t.baseStats.attackSpeed = 40f;
		this.t.baseStats.damage = 10;
		this.t.icon = "iconTumor";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#FF49CB");
		this.t.job = "tumor_monster";
		this.t.texture_path = "t_tumor_monster_unit";
		this.t.texture_heads = "t_tumor_monster_unit_heads";
		this.t.use_items = true;
		this.t.take_items = true;
		this.t.disableJumpAnimation = true;
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.addTrait("immortal");
		this.addTrait("weightless");
		this.addTrait("ugly");
		this.clone("tumor_monster_animal", "tumor_monster_unit");
		this.t.texture_path = "t_tumor_monster_animal";
		this.t.body_separate_part_hands = false;
		this.t.body_separate_part_head = false;
		this.t.use_items = false;
		this.t.take_items = false;
		this.clone("lil_pumpkin", "tumor_monster_animal");
		this.t.texture_path = "t_lil_pumpkin";
		this.t.nameTemplate = "lil_pumpkin_name";
		this.t.race = "super_pumpkins";
		this.t.kingdom = "super_pumpkins";
		this.t.immune_to_slowness = true;
		this.t.clearTraits();
		this.addTrait("attractive");
		this.addTrait("fat");
		this.addTrait("bloodlust");
		this.clone("assimilator", "tumor_monster_animal");
		this.t.texture_path = "t_assimilator";
		this.t.nameTemplate = "assimilator_name";
		this.t.canTurnIntoMush = false;
		this.t.race = "assimilators";
		this.t.kingdom = "assimilators";
		this.t.baseStats.damage = 0;
		this.t.baseStats.attackSpeed = 0f;
		this.addTrait("fire_proof");
		this.removeTrait("ugly");
		this.removeTrait("weightless");
		this.t.damagedByOcean = true;
		this.t.damagedByRain = true;
		this.t.defaultAttack = "shotgun";
		this.clone("bioblob", "tumor_monster_animal");
		this.t.texture_path = "t_bioblob";
		this.t.nameTemplate = "bioblob_name";
		this.t.race = "biomass";
		this.t.kingdom = "biomass";
		this.t.immune_to_slowness = true;
		this.addTrait("strong_minded");
		this.addTrait("ugly");
		this.clone("walker", "_mob");
		this.t.nameLocale = "Cold Ones";
		this.t.nameTemplate = "cold_one_name";
		this.t.body_separate_part_head = true;
		this.t.race = "walker";
		this.t.kingdom = "walkers";
		this.t.baseStats.speed = 20f;
		this.t.baseStats.attackSpeed = 160f;
		this.t.baseStats.damage = 40;
		this.t.baseStats.knockback = 1f;
		this.t.baseStats.targets = 2;
		this.t.icon = "iconWalker";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#90D2D4");
		this.t.canTurnIntoZombie = true;
		this.t.zombieID = "zombie";
		this.t.skeletonID = "skeleton_cursed";
		this.t.job = "move_mob";
		this.t.texture_path = "t_walker";
		this.t.texture_heads = "t_walker_heads";
		this.t.animation_walk = "walk_0,walk_1,walk_2,walk_3";
		this.t.animation_swim = "swim_0,swim_1,swim_2,swim_3";
		this.t.disableJumpAnimation = true;
		this.t.have_soul = true;
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.addTrait("cold_aura");
		this.addTrait("weightless");
		this.addTrait("freeze_proof");
		this.clone("livingPlants", "_mob");
		this.t.nameLocale = "Living Plants";
		this.t.actorSize = ActorSize.S15_Bear;
		this.t.shadowTexture = "unitShadow_6";
		this.t.nameTemplate = "living_plant_name";
		this.t.race = "livingPlants";
		this.t.kingdom = "living_plants";
		this.t.baseStats.health = 300;
		this.t.baseStats.speed = 10f;
		this.t.baseStats.armor = 0;
		this.t.baseStats.attackSpeed = 70f;
		this.t.baseStats.damage = 30;
		this.t.baseStats.knockback = 1.2f;
		this.t.baseStats.knockbackReduction = 80f;
		this.t.baseStats.targets = 3;
		this.t.damagedByOcean = true;
		this.t.icon = "iconLivingPlants";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#115D11");
		this.t.rotatingAnimation = true;
		this.t.disableJumpAnimation = false;
		this.t.specialAnimation = true;
		this.t.inspectAvatarScale = 1f;
		this.t.baseStats.scale = 0.25f;
		this.t.canTurnIntoMush = false;
		this.t.canTurnIntoTumorMonster = false;
		this.addTrait("immortal");
		this.addTrait("regeneration");
		this.clone("livingHouse", "_mob");
		this.t.nameLocale = "Living Houses";
		this.t.actorSize = ActorSize.S15_Bear;
		this.t.shadowTexture = "unitShadow_6";
		this.t.nameTemplate = "homie_name";
		this.t.race = "livingHouse";
		this.t.kingdom = "living_houses";
		this.t.baseStats.health = 500;
		this.t.baseStats.armor = 1;
		this.t.baseStats.speed = 10f;
		this.t.baseStats.attackSpeed = 60f;
		this.t.baseStats.damage = 50;
		this.t.baseStats.knockback = 1.4f;
		this.t.baseStats.knockbackReduction = 80f;
		this.t.baseStats.targets = 3;
		this.t.damagedByOcean = true;
		this.t.icon = "iconLivingHouse";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#24803E");
		this.t.rotatingAnimation = true;
		this.t.disableJumpAnimation = false;
		this.t.specialAnimation = true;
		this.t.inspectAvatarScale = 1f;
		this.t.baseStats.scale = 0.25f;
		this.t.canTurnIntoMush = false;
		this.t.canTurnIntoTumorMonster = false;
		this.addTrait("immortal");
		this.clone("greg", "_mob");
		this.t.nameLocale = "Greg";
		this.t.actorSize = ActorSize.S15_Bear;
		this.t.shadowTexture = "unitShadow_6";
		this.t.texture_path = "t_greg";
		this.t.animation_walk = "walk_0";
		this.t.animation_swim = "walk_0";
		this.t.race = "greg";
		this.t.kingdom = "greg";
		this.t.baseStats.health = 1000;
		this.t.baseStats.armor = 1;
		this.t.baseStats.speed = 5f;
		this.t.baseStats.attackSpeed = 60f;
		this.t.baseStats.damage = 20;
		this.t.baseStats.knockback = 1.4f;
		this.t.baseStats.knockbackReduction = 80f;
		this.t.baseStats.targets = 3;
		this.t.damagedByOcean = true;
		this.t.icon = "iconGreg";
		this.t.needFood = false;
		this.t.color = Toolbox.makeColor("#24803E");
		this.t.rotatingAnimation = true;
		this.t.nameTemplate = "greg_name";
		this.t.have_soul = true;
		this.addTrait("immortal");
		ActorStats actorStats15 = new ActorStats();
		actorStats15.id = "_boat";
		actorStats15.race = "boat";
		actorStats15.canBeKilledByStuff = true;
		actorStats15.canBeKilledByLifeEraser = true;
		actorStats15.canAttackBuildings = true;
		actorStats15.canBeMovedByPowers = true;
		actorStats15.canBeHurtByPowers = true;
		actorStats15.updateZ = true;
		actorStats15.effectDamage = true;
		actorStats15.dieOnGround = true;
		actorStats15.oceanCreature = true;
		actorStats15.shadow = false;
		actorStats15.isBoat = true;
		actorStats15.kingdom = "neutral_animals";
		actorStats15.skipFightLogic = true;
		actorStats15.canBeInspected = true;
		actorStats15.hideOnMinimap = true;
		actorStats15.inspect_stats = false;
		actorStats15.inspect_children = false;
		actorStats15.inspect_experience = false;
		actorStats15.inspect_kills = false;
		actorStats15.inspect_home = true;
		actorStats15.specialAnimation = true;
		actorStats15.immune_to_injuries = true;
		actorStats15.prefab = "p_boat";
		actorStats15.sprite_group_renderer = true;
		pAsset = actorStats15;
		this.t = actorStats15;
		this.add(pAsset);
		this.t.texture_atlas = UnitTextureAtlasID.Boats;
		this.t.nameLocale = "Boats";
		this.t.inspectAvatarScale = 1f;
		this.t.color = Toolbox.makeColor("#000000");
		this.t.baseStats.scale = 0.25f;
		this.t.baseStats.knockbackReduction = 100f;
		this.addTrait("boat");
		this.clone("boat_trading", "_boat");
		this.t.baseStats.health = 1000;
		this.t.baseStats.armor = 50;
		this.t.baseStats.speed = 140f;
		this.t.drawBoatMark = true;
		this.t.job = "boat_trading";
		this.t.tech = "boats_trading";
		this.t.cost = new ConstructionCost(10, 0, 0, 10);
		this.clone("boat_transport", "_boat");
		this.t.baseStats.speed = 120f;
		this.t.baseStats.health = 1500;
		this.t.baseStats.armor = 60;
		this.t.drawBoatMark = true;
		this.t.job = "boat_transport";
		this.t.tech = "boats_transport";
		this.t.cost = new ConstructionCost(5, 0, 2, 20);
		this.clone("boat_fishing", "_boat");
		this.t.baseStats.speed = 60f;
		this.t.baseStats.health = 500;
		this.t.baseStats.armor = 50;
		this.t.job = "boat_fishing";
		this.t.cost = new ConstructionCost(5, 0, 0, 5);
		Debug.Log("GENERATE ACTOR STATS " + this.list.Count.ToString());
		this.spawnInRuins.Add("rat");
		for (int i = 0; i < this.list.Count; i++)
		{
			ActorStats actorStats16 = this.list[i];
			this.t = actorStats16;
			if (actorStats16.shadow)
			{
				this.loadShadow(actorStats16);
			}
			if (!actorStats16.id.Contains("_") && actorStats16.actorSize <= ActorSize.S2_Crab)
			{
				this.addTrait("weightless");
			}
		}
	}

	// Token: 0x060000C0 RID: 192 RVA: 0x0000F9B4 File Offset: 0x0000DBB4
	public void addColorSet(string pID, string pColorFrom, string pColorTo)
	{
		this.t.useSkinColors = true;
		if (this.t.color_sets == null)
		{
			this.t.color_sets = new List<ColorSet>();
		}
		ColorSet colorSet = new ColorSet();
		colorSet.id = pID;
		this.t.color_sets.Add(colorSet);
		Color pFrom = Toolbox.makeColor(pColorFrom);
		Color pTo = Toolbox.makeColor(pColorTo);
		int num = 5;
		float num2 = 1f / (float)(num - 1);
		for (int i = 0; i < num; i++)
		{
			float num3 = 1f - (float)i * num2;
			if (num3 > 1f)
			{
				num3 = 1f;
			}
			Color c = Toolbox.blendColor(pFrom, pTo, num3);
			colorSet.colors.Add(c);
		}
	}

	// Token: 0x060000C1 RID: 193 RVA: 0x0000FA70 File Offset: 0x0000DC70
	public void setZombie()
	{
		this.t.nameLocale = "Zombie";
		this.t.canAttackBrains = true;
		this.t.race = "undead";
		this.t.kingdom = "undead";
		this.t.take_items = false;
		this.t.take_items_ignore_range_weapons = true;
		this.addTrait("zombie");
		this.addTrait("immortal");
		this.addTrait("stupid");
		this.removeTrait("fast");
		this.removeTrait("agile");
		this.removeTrait("genius");
		this.t.canTurnIntoZombie = false;
		this.t.needFood = false;
		this.t.zombieID = "";
		this.t.job = "move_mob";
		this.t.canTurnIntoMush = false;
	}

	// Token: 0x060000C2 RID: 194 RVA: 0x0000FB57 File Offset: 0x0000DD57
	public void addFlag(string pFlag)
	{
		this.t.flags.Add(pFlag);
	}

	// Token: 0x060000C3 RID: 195 RVA: 0x0000FB6C File Offset: 0x0000DD6C
	public void clear()
	{
		for (int i = 0; i < this.list.Count; i++)
		{
			this.list[i].currentAmount = 0;
		}
	}

	// Token: 0x060000C4 RID: 196 RVA: 0x0000FBA4 File Offset: 0x0000DDA4
	internal void addTrait(string pTrait)
	{
		if (this.t.traits == null)
		{
			this.t.traits = new List<string>();
		}
		if (!this.t.traits.Contains(pTrait))
		{
			this.t.traits.Add(pTrait);
		}
	}

	// Token: 0x060000C5 RID: 197 RVA: 0x0000FBF2 File Offset: 0x0000DDF2
	private void removeTrait(string pTrait)
	{
		if (this.t.traits == null)
		{
			this.t.traits = new List<string>();
		}
		this.t.traits.Remove(pTrait);
	}

	// Token: 0x060000C6 RID: 198 RVA: 0x0000FC24 File Offset: 0x0000DE24
	internal void loadShadow(ActorStats pActorStat)
	{
		if (!ActorStatsLibrary.shadowSprites.ContainsKey(pActorStat.shadowTexture))
		{
			Sprite sprite = Resources.Load<Sprite>("shadows/" + pActorStat.shadowTexture);
			if (sprite == null)
			{
				Debug.LogError("Shadow not found " + pActorStat.shadowTexture + " for " + pActorStat.id);
			}
			ActorStatsLibrary.shadowSprites.Add(pActorStat.shadowTexture, sprite);
		}
		pActorStat.shadow_sprite = ActorStatsLibrary.shadowSprites[pActorStat.shadowTexture];
	}

	// Token: 0x0400005E RID: 94
	public List<string> spawnInRuins = new List<string>();

	// Token: 0x0400005F RID: 95
	private static Dictionary<string, Sprite> shadowSprites = new Dictionary<string, Sprite>();
}
