using System;

// Token: 0x0200006D RID: 109
public class ItemWeaponMaterialLibrary : ItemAssetLibrary<ItemAsset>
{
	// Token: 0x06000238 RID: 568 RVA: 0x00029D74 File Offset: 0x00027F74
	public override void init()
	{
		base.init();
		ItemAsset itemAsset = new ItemAsset();
		itemAsset.id = "base";
		ItemAsset pAsset = itemAsset;
		this.t = itemAsset;
		this.add(pAsset);
		ItemAsset itemAsset2 = new ItemAsset();
		itemAsset2.id = "wood";
		itemAsset2.equipment_value = 1;
		pAsset = itemAsset2;
		this.t = itemAsset2;
		this.add(pAsset);
		this.t.setCost(1, "wood", 1, "none", 0);
		this.t.baseStats.damage = 1;
		this.t.baseStats.attackSpeed = 1f;
		ItemAsset itemAsset3 = new ItemAsset();
		itemAsset3.id = "stone";
		itemAsset3.equipment_value = 10;
		pAsset = itemAsset3;
		this.t = itemAsset3;
		this.add(pAsset);
		this.t.setCost(1, "stone", 1, "none", 0);
		this.t.baseStats.damage = 3;
		this.t.baseStats.speed = -2f;
		this.t.baseStats.attackSpeed = -10f;
		ItemAsset itemAsset4 = new ItemAsset();
		itemAsset4.id = "copper";
		itemAsset4.equipment_value = 10;
		itemAsset4.tech_needed = "material_copper";
		pAsset = itemAsset4;
		this.t = itemAsset4;
		this.add(pAsset);
		this.t.setCost(1, "metals", 1, "none", 0);
		this.t.baseStats.damage = 3;
		this.t.baseStats.attackSpeed = 2f;
		ItemAsset itemAsset5 = new ItemAsset();
		itemAsset5.id = "bronze";
		itemAsset5.equipment_value = 15;
		itemAsset5.tech_needed = "material_bronze";
		pAsset = itemAsset5;
		this.t = itemAsset5;
		this.add(pAsset);
		this.t.setCost(5, "metals", 1, "none", 0);
		this.t.baseStats.damage = 4;
		this.t.baseStats.attackSpeed = 5f;
		ItemAsset itemAsset6 = new ItemAsset();
		itemAsset6.id = "silver";
		itemAsset6.equipment_value = 20;
		itemAsset6.tech_needed = "material_silver";
		pAsset = itemAsset6;
		this.t = itemAsset6;
		this.add(pAsset);
		this.t.setCost(10, "metals", 1, "none", 0);
		this.t.baseStats.damage = 5;
		this.t.baseStats.damage = 1;
		this.t.baseStats.attackSpeed = 8f;
		ItemAsset itemAsset7 = new ItemAsset();
		itemAsset7.id = "iron";
		itemAsset7.equipment_value = 30;
		itemAsset7.tech_needed = "material_iron";
		pAsset = itemAsset7;
		this.t = itemAsset7;
		this.add(pAsset);
		this.t.setCost(15, "metals", 2, "none", 0);
		this.t.baseStats.damage = 6;
		this.t.baseStats.attackSpeed = 10f;
		this.t.baseStats.crit = 5f;
		ItemAsset itemAsset8 = new ItemAsset();
		itemAsset8.id = "steel";
		itemAsset8.equipment_value = 40;
		itemAsset8.tech_needed = "material_steel";
		pAsset = itemAsset8;
		this.t = itemAsset8;
		this.add(pAsset);
		this.t.setCost(20, "metals", 3, "none", 0);
		this.t.baseStats.damage = 7;
		this.t.baseStats.speed = 1f;
		this.t.baseStats.attackSpeed = 10f;
		this.t.baseStats.crit = 5f;
		ItemAsset itemAsset9 = new ItemAsset();
		itemAsset9.id = "mythril";
		itemAsset9.equipment_value = 50;
		itemAsset9.tech_needed = "material_mythril";
		pAsset = itemAsset9;
		this.t = itemAsset9;
		this.add(pAsset);
		this.t.setCost(50, "metals", 4, "none", 0);
		this.t.baseStats.damage = 8;
		this.t.baseStats.attackSpeed = 10f;
		this.t.baseStats.crit = 5f;
		ItemAsset itemAsset10 = new ItemAsset();
		itemAsset10.id = "adamantine";
		itemAsset10.equipment_value = 70;
		itemAsset10.tech_needed = "material_adamantine";
		pAsset = itemAsset10;
		this.t = itemAsset10;
		this.add(pAsset);
		this.t.setCost(100, "metals", 5, "none", 0);
		this.t.baseStats.damage = 10;
		this.t.baseStats.speed = 1f;
		this.t.baseStats.attackSpeed = 15f;
		this.t.baseStats.crit = 15f;
	}
}
