using System;
using Beebyte.Obfuscator;

// Token: 0x0200006A RID: 106
[ObfuscateLiterals]
public class ItemPrefixLibrary : AssetLibrary<ItemAsset>
{
	// Token: 0x0600022E RID: 558 RVA: 0x00028F20 File Offset: 0x00027120
	public override void init()
	{
		base.init();
		ItemAsset itemAsset = new ItemAsset();
		itemAsset.id = "0";
		itemAsset.rarity = 60;
		itemAsset.pool = "melee,range,equipment";
		ItemAsset pAsset = itemAsset;
		this.t = itemAsset;
		this.add(pAsset);
		ItemAsset itemAsset2 = new ItemAsset();
		itemAsset2.id = "uncomfortable";
		itemAsset2.rarity = 30;
		itemAsset2.equipment_value = -10;
		itemAsset2.pool = "equipment";
		itemAsset2.quality = ItemQuality.Junk;
		pAsset = itemAsset2;
		this.t = itemAsset2;
		this.add(pAsset);
		this.t.baseStats.dodge = -10f;
		ItemAsset itemAsset3 = new ItemAsset();
		itemAsset3.id = "blunt";
		itemAsset3.rarity = 10;
		itemAsset3.equipment_value = -20;
		itemAsset3.pool = "melee";
		itemAsset3.quality = ItemQuality.Junk;
		pAsset = itemAsset3;
		this.t = itemAsset3;
		this.add(pAsset);
		this.t.baseStats.accuracy = -8f;
		this.t.baseStats.dodge = -5f;
		ItemAsset itemAsset4 = new ItemAsset();
		itemAsset4.id = "crooked";
		itemAsset4.rarity = 10;
		itemAsset4.equipment_value = -20;
		itemAsset4.pool = "melee";
		itemAsset4.quality = ItemQuality.Junk;
		pAsset = itemAsset4;
		this.t = itemAsset4;
		this.add(pAsset);
		this.t.baseStats.accuracy = -10f;
		this.t.baseStats.dodge = -10f;
		this.t.baseStats.armor = -5;
		ItemAsset itemAsset5 = new ItemAsset();
		itemAsset5.id = "bad";
		itemAsset5.rarity = 10;
		itemAsset5.equipment_value = -10;
		itemAsset5.pool = "range,melee,equipment";
		itemAsset5.quality = ItemQuality.Junk;
		pAsset = itemAsset5;
		this.t = itemAsset5;
		this.add(pAsset);
		this.t.baseStats.accuracy = -20f;
		this.t.baseStats.dodge = -5f;
		this.t.baseStats.attackSpeed = -10f;
		ItemAsset itemAsset6 = new ItemAsset();
		itemAsset6.id = "ugly";
		itemAsset6.rarity = 5;
		itemAsset6.equipment_value = -30;
		itemAsset6.pool = "melee,equipment";
		itemAsset6.quality = ItemQuality.Junk;
		pAsset = itemAsset6;
		this.t = itemAsset6;
		this.add(pAsset);
		this.t.baseStats.diplomacy = -5;
		ItemAsset itemAsset7 = new ItemAsset();
		itemAsset7.id = "broken";
		itemAsset7.rarity = 5;
		itemAsset7.equipment_value = -30;
		itemAsset7.pool = "melee,range,equipment";
		itemAsset7.quality = ItemQuality.Junk;
		pAsset = itemAsset7;
		this.t = itemAsset7;
		this.add(pAsset);
		this.t.baseStats.damage = -3;
		this.t.baseStats.accuracy = -3f;
		this.t.baseStats.attackSpeed = -20f;
		ItemAsset itemAsset8 = new ItemAsset();
		itemAsset8.id = "good";
		itemAsset8.rarity = 10;
		itemAsset8.equipment_value = 5;
		itemAsset8.pool = "melee,range,equipment";
		itemAsset8.quality = ItemQuality.Rare;
		pAsset = itemAsset8;
		this.t = itemAsset8;
		this.add(pAsset);
		this.t.baseStats.accuracy = 5f;
		this.t.baseStats.speed = 1f;
		ItemAsset itemAsset9 = new ItemAsset();
		itemAsset9.id = "fine";
		itemAsset9.rarity = 5;
		itemAsset9.equipment_value = 10;
		itemAsset9.pool = "melee,range,equipment";
		itemAsset9.quality = ItemQuality.Rare;
		pAsset = itemAsset9;
		this.t = itemAsset9;
		this.add(pAsset);
		this.t.baseStats.accuracy = 7f;
		this.t.baseStats.speed = 1f;
		this.t.baseStats.damage = 1;
		ItemAsset itemAsset10 = new ItemAsset();
		itemAsset10.id = "elegant";
		itemAsset10.rarity = 10;
		itemAsset10.equipment_value = 10;
		itemAsset10.pool = "equipment";
		itemAsset10.quality = ItemQuality.Rare;
		pAsset = itemAsset10;
		this.t = itemAsset10;
		this.add(pAsset);
		this.t.baseStats.dodge = 5f;
		this.t.baseStats.accuracy = 10f;
		this.t.baseStats.crit = 5f;
		ItemAsset itemAsset11 = new ItemAsset();
		itemAsset11.id = "sharp";
		itemAsset11.rarity = 5;
		itemAsset11.equipment_value = 10;
		itemAsset11.pool = "melee";
		itemAsset11.quality = ItemQuality.Rare;
		pAsset = itemAsset11;
		this.t = itemAsset11;
		this.add(pAsset);
		this.t.baseStats.damage = 3;
		this.t.baseStats.crit = 20f;
		ItemAsset itemAsset12 = new ItemAsset();
		itemAsset12.id = "huge";
		itemAsset12.rarity = 5;
		itemAsset12.equipment_value = 10;
		itemAsset12.pool = "melee";
		itemAsset12.quality = ItemQuality.Rare;
		pAsset = itemAsset12;
		this.t = itemAsset12;
		this.add(pAsset);
		this.t.baseStats.speed = -2f;
		this.t.baseStats.damage = 5;
		this.t.baseStats.targets = 3;
		ItemAsset itemAsset13 = new ItemAsset();
		itemAsset13.id = "great";
		itemAsset13.rarity = 4;
		itemAsset13.equipment_value = 20;
		itemAsset13.pool = "melee,equipment,range";
		itemAsset13.quality = ItemQuality.Epic;
		pAsset = itemAsset13;
		this.t = itemAsset13;
		this.add(pAsset);
		this.t.baseStats.damage = 4;
		ItemAsset itemAsset14 = new ItemAsset();
		itemAsset14.id = "perfect";
		itemAsset14.rarity = 3;
		itemAsset14.equipment_value = 20;
		itemAsset14.pool = "melee,equipment,range";
		itemAsset14.quality = ItemQuality.Epic;
		pAsset = itemAsset14;
		this.t = itemAsset14;
		this.add(pAsset);
		this.t.baseStats.health = 20;
		this.t.baseStats.damage = 2;
		ItemAsset itemAsset15 = new ItemAsset();
		itemAsset15.id = "battle";
		itemAsset15.rarity = 3;
		itemAsset15.equipment_value = 20;
		itemAsset15.pool = "melee";
		itemAsset15.quality = ItemQuality.Legendary;
		pAsset = itemAsset15;
		this.t = itemAsset15;
		this.add(pAsset);
		this.t.baseStats.damage = 5;
		this.t.baseStats.crit = 20f;
		this.t.baseStats.armor = 3;
		this.t.baseStats.targets = 1;
		ItemAsset itemAsset16 = new ItemAsset();
		itemAsset16.id = "death";
		itemAsset16.rarity = 3;
		itemAsset16.equipment_value = 30;
		itemAsset16.pool = "melee,range";
		itemAsset16.quality = ItemQuality.Legendary;
		pAsset = itemAsset16;
		this.t = itemAsset16;
		this.add(pAsset);
		this.t.baseStats.damage = 20;
		this.t.baseStats.health = -60;
		this.t.baseStats.armor = -2;
		this.t.baseStats.targets = 1;
		ItemAsset itemAsset17 = new ItemAsset();
		itemAsset17.id = "monster";
		itemAsset17.rarity = 3;
		itemAsset17.equipment_value = 40;
		itemAsset17.pool = "melee,range";
		itemAsset17.quality = ItemQuality.Legendary;
		pAsset = itemAsset17;
		this.t = itemAsset17;
		this.add(pAsset);
		this.t.baseStats.health = 100;
		this.t.baseStats.damage = 10;
		this.t.baseStats.crit = 5f;
		this.t.baseStats.targets = 2;
		ItemAsset itemAsset18 = new ItemAsset();
		itemAsset18.id = "wild";
		itemAsset18.rarity = 3;
		itemAsset18.equipment_value = 30;
		itemAsset18.pool = "melee,range";
		itemAsset18.quality = ItemQuality.Legendary;
		pAsset = itemAsset18;
		this.t = itemAsset18;
		this.add(pAsset);
		this.t.baseStats.speed = 5f;
		this.t.baseStats.crit = 30f;
		this.t.baseStats.damage = 6;
		this.t.baseStats.targets = 1;
	}
}
