using System;

// Token: 0x0200006B RID: 107
public class ItemSuffixLibrary : AssetLibrary<ItemAsset>
{
	// Token: 0x06000230 RID: 560 RVA: 0x00029728 File Offset: 0x00027928
	public override void init()
	{
		base.init();
		ItemAsset itemAsset = new ItemAsset();
		itemAsset.id = "0";
		itemAsset.rarity = 40;
		itemAsset.pool = "melee,equipment,range";
		ItemAsset pAsset = itemAsset;
		this.t = itemAsset;
		this.add(pAsset);
		ItemAsset itemAsset2 = new ItemAsset();
		itemAsset2.id = "balance";
		itemAsset2.rarity = 2;
		itemAsset2.equipment_value = 5;
		itemAsset2.pool = "melee,range";
		itemAsset2.quality = ItemQuality.Rare;
		pAsset = itemAsset2;
		this.t = itemAsset2;
		this.add(pAsset);
		this.t.baseStats.crit = 30f;
		ItemAsset itemAsset3 = new ItemAsset();
		itemAsset3.id = "justice";
		itemAsset3.rarity = 1;
		itemAsset3.equipment_value = 10;
		itemAsset3.pool = "melee,equipment,range";
		itemAsset3.quality = ItemQuality.Rare;
		pAsset = itemAsset3;
		this.t = itemAsset3;
		this.add(pAsset);
		this.t.baseStats.armor = 5;
		this.t.baseStats.health = 20;
		ItemAsset itemAsset4 = new ItemAsset();
		itemAsset4.id = "truth";
		itemAsset4.rarity = 1;
		itemAsset4.equipment_value = 10;
		itemAsset4.pool = "melee,equipment,range";
		itemAsset4.quality = ItemQuality.Rare;
		pAsset = itemAsset4;
		this.t = itemAsset4;
		this.add(pAsset);
		this.t.baseStats.diplomacy = 1;
		ItemAsset itemAsset5 = new ItemAsset();
		itemAsset5.id = "speed";
		itemAsset5.rarity = 3;
		itemAsset5.equipment_value = 10;
		itemAsset5.pool = "melee,equipment,range";
		itemAsset5.quality = ItemQuality.Rare;
		pAsset = itemAsset5;
		this.t = itemAsset5;
		this.add(pAsset);
		this.t.baseStats.speed = 6f;
		ItemAsset itemAsset6 = new ItemAsset();
		itemAsset6.id = "health";
		itemAsset6.rarity = 1;
		itemAsset6.equipment_value = 10;
		itemAsset6.pool = "melee,equipment,range";
		itemAsset6.quality = ItemQuality.Epic;
		pAsset = itemAsset6;
		this.t = itemAsset6;
		this.add(pAsset);
		this.t.baseStats.health = 100;
		ItemAsset itemAsset7 = new ItemAsset();
		itemAsset7.id = "protection";
		itemAsset7.rarity = 1;
		itemAsset7.equipment_value = 15;
		itemAsset7.pool = "melee,equipment,range";
		itemAsset7.quality = ItemQuality.Epic;
		pAsset = itemAsset7;
		this.t = itemAsset7;
		this.add(pAsset);
		this.t.baseStats.armor = 6;
		ItemAsset itemAsset8 = new ItemAsset();
		itemAsset8.id = "greatness";
		itemAsset8.rarity = 1;
		itemAsset8.equipment_value = 20;
		itemAsset8.pool = "melee,equipment,range";
		itemAsset8.quality = ItemQuality.Epic;
		pAsset = itemAsset8;
		this.t = itemAsset8;
		this.add(pAsset);
		this.t.baseStats.dodge = 10f;
		ItemAsset itemAsset9 = new ItemAsset();
		itemAsset9.id = "power";
		itemAsset9.rarity = 3;
		itemAsset9.equipment_value = 25;
		itemAsset9.pool = "melee,equipment,range";
		itemAsset9.quality = ItemQuality.Epic;
		pAsset = itemAsset9;
		this.t = itemAsset9;
		this.add(pAsset);
		this.t.baseStats.damage = 5;
		ItemAsset itemAsset10 = new ItemAsset();
		itemAsset10.id = "hell";
		itemAsset10.rarity = 1;
		itemAsset10.equipment_value = 30;
		itemAsset10.pool = "melee,equipment";
		itemAsset10.quality = ItemQuality.Legendary;
		pAsset = itemAsset10;
		this.t = itemAsset10;
		this.add(pAsset);
		this.t.baseStats.damage = 10;
		ItemAsset itemAsset11 = new ItemAsset();
		itemAsset11.id = "doom";
		itemAsset11.rarity = 1;
		itemAsset11.equipment_value = 31;
		itemAsset11.pool = "melee,equipment,range";
		itemAsset11.quality = ItemQuality.Legendary;
		pAsset = itemAsset11;
		this.t = itemAsset11;
		this.add(pAsset);
		this.t.baseStats.damage = 10;
		this.t.baseStats.accuracy = 10f;
		this.t.baseStats.crit = 20f;
		ItemAsset itemAsset12 = new ItemAsset();
		itemAsset12.id = "terror";
		itemAsset12.rarity = 1;
		itemAsset12.equipment_value = 35;
		itemAsset12.pool = "melee,equipment,range";
		itemAsset12.quality = ItemQuality.Legendary;
		pAsset = itemAsset12;
		this.t = itemAsset12;
		this.add(pAsset);
		this.t.baseStats.damage = 10;
		this.t.baseStats.crit = 30f;
		this.t.baseStats.attackSpeed = 10f;
		this.t.baseStats.speed = 10f;
		this.t.baseStats.armor = 5;
	}
}
