using System;

namespace ai.behaviours
{
	// Token: 0x02000397 RID: 919
	public class BehaviourTaskActorLibrary : AssetLibrary<BehaviourTaskActor>
	{
		// Token: 0x060013D0 RID: 5072 RVA: 0x000A4110 File Offset: 0x000A2310
		public override void init()
		{
			base.init();
			this.initTasksBoats();
			this.initTasksMobs();
			BehaviourTaskActor behaviourTaskActor = new BehaviourTaskActor();
			behaviourTaskActor.id = "nothing";
			BehaviourTaskActor pAsset = behaviourTaskActor;
			this.t = behaviourTaskActor;
			this.add(pAsset);
			BehaviourTaskActor behaviourTaskActor2 = new BehaviourTaskActor();
			behaviourTaskActor2.id = "fight";
			behaviourTaskActor2.fighting = true;
			pAsset = behaviourTaskActor2;
			this.t = behaviourTaskActor2;
			this.add(pAsset);
			this.t.addBeh(new BehFightCheckEnemyIsOk());
			this.t.addBeh(new BehGoToActorTarget("sameTile", true));
			this.t.addBeh(new BehRestartTask());
			BehaviourTaskActor behaviourTaskActor3 = new BehaviourTaskActor();
			behaviourTaskActor3.id = "move_from_block";
			behaviourTaskActor3.moveFromBlock = true;
			behaviourTaskActor3.ignoreFightCheck = true;
			pAsset = behaviourTaskActor3;
			this.t = behaviourTaskActor3;
			this.add(pAsset);
			this.t.addBeh(new BehMoveAwayFromBlock());
			this.t.addBeh(new BehGoToTileTarget
			{
				walkOnWater = true,
				walkOnBlocks = true
			});
			BehaviourTaskActor behaviourTaskActor4 = new BehaviourTaskActor();
			behaviourTaskActor4.id = "swim_to_island";
			behaviourTaskActor4.ignoreFightCheck = true;
			behaviourTaskActor4.swim_to_island = true;
			pAsset = behaviourTaskActor4;
			this.t = behaviourTaskActor4;
			this.add(pAsset);
			this.t.addBeh(new BehSwimToIsland());
			this.t.addBeh(new BehGoOrSwimToTileTarget());
			BehaviourTaskActor behaviourTaskActor5 = new BehaviourTaskActor();
			behaviourTaskActor5.id = "check_if_stuck_on_small_land";
			behaviourTaskActor5.ignoreFightCheck = true;
			pAsset = behaviourTaskActor5;
			this.t = behaviourTaskActor5;
			this.add(pAsset);
			this.t.addBeh(new BehCheckIfOnSmallLand());
			this.t.addBeh(new BehWalkIntoWaterCorner());
			this.t.addBeh(new BehGoOrSwimToTileTarget());
			BehaviourTaskActor behaviourTaskActor6 = new BehaviourTaskActor();
			behaviourTaskActor6.id = "pollinate";
			pAsset = behaviourTaskActor6;
			this.t = behaviourTaskActor6;
			this.add(pAsset);
			this.t.addBeh(new BehBeeCheckHome());
			this.t.addBeh(new BehFindBuilding("flower"));
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 3f));
			this.t.addBeh(new BehBeePollinate());
			this.t.addBeh(new BehBeeCheckReturnHome());
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehBeeReturnHome());
			BehaviourTaskActor behaviourTaskActor7 = new BehaviourTaskActor();
			behaviourTaskActor7.id = "random_move";
			pAsset = behaviourTaskActor7;
			this.t = behaviourTaskActor7;
			this.add(pAsset);
			this.t.addBeh(new BehFindRandomTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 6f));
			BehaviourTaskActor behaviourTaskActor8 = new BehaviourTaskActor();
			behaviourTaskActor8.id = "random_animal_move";
			pAsset = behaviourTaskActor8;
			this.t = behaviourTaskActor8;
			this.add(pAsset);
			this.t.addBeh(new BehAnimalFindTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(3f, 6f));
			BehaviourTaskActor behaviourTaskActor9 = new BehaviourTaskActor();
			behaviourTaskActor9.id = "random_move_towards_civ_building";
			pAsset = behaviourTaskActor9;
			this.t = behaviourTaskActor9;
			this.add(pAsset);
			this.t.addBeh(new BehFindRandomCivBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 4f));
			BehaviourTaskActor behaviourTaskActor10 = new BehaviourTaskActor();
			behaviourTaskActor10.id = "stay_in_house";
			pAsset = behaviourTaskActor10;
			this.t = behaviourTaskActor10;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("random_house_building"));
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehStayInBuildingTarget(10f, 60f));
			this.t.addBeh(new BehExitBuilding());
			BehaviourTaskActor behaviourTaskActor11 = new BehaviourTaskActor();
			behaviourTaskActor11.id = "random_swim";
			pAsset = behaviourTaskActor11;
			this.t = behaviourTaskActor11;
			this.add(pAsset);
			this.t.addBeh(new BehRandomSwim());
			this.t.addBeh(new BehRandomWait(0f, 2f));
			BehaviourTaskActor behaviourTaskActor12 = new BehaviourTaskActor();
			behaviourTaskActor12.id = "check_join_city";
			pAsset = behaviourTaskActor12;
			this.t = behaviourTaskActor12;
			this.add(pAsset);
			this.t.addBeh(new BehJoinCity());
			this.t.addBeh(new BehEndJob());
			BehaviourTaskActor behaviourTaskActor13 = new BehaviourTaskActor();
			behaviourTaskActor13.id = "check_join_empty_nearby_city";
			pAsset = behaviourTaskActor13;
			this.t = behaviourTaskActor13;
			this.add(pAsset);
			this.t.addBeh(new BehFindEmptyNearbyCity());
			this.t.addBeh(new BehEndJob());
			BehaviourTaskActor behaviourTaskActor14 = new BehaviourTaskActor();
			behaviourTaskActor14.id = "become_citizen";
			pAsset = behaviourTaskActor14;
			this.t = behaviourTaskActor14;
			this.add(pAsset);
			this.t.addBeh(new BehCheckCitizenJob());
			BehaviourTaskActor behaviourTaskActor15 = new BehaviourTaskActor();
			behaviourTaskActor15.id = "end_job";
			pAsset = behaviourTaskActor15;
			this.t = behaviourTaskActor15;
			this.add(pAsset);
			this.t.addBeh(new BehEndJob());
			BehaviourTaskActor behaviourTaskActor16 = new BehaviourTaskActor();
			behaviourTaskActor16.id = "build_city_here";
			pAsset = behaviourTaskActor16;
			this.t = behaviourTaskActor16;
			this.add(pAsset);
			this.t.addBeh(new BehCheckBuildCity());
			this.t.addBeh(new BehEndJob());
			BehaviourTaskActor behaviourTaskActor17 = new BehaviourTaskActor();
			behaviourTaskActor17.id = "nomad_try_build_city";
			pAsset = behaviourTaskActor17;
			this.t = behaviourTaskActor17;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(1f, 5f));
			this.t.addBeh(new BehFindTileForCity());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehCheckBuildCity());
			this.t.addBeh(new BehEndJob());
			BehaviourTaskActor behaviourTaskActor18 = new BehaviourTaskActor();
			behaviourTaskActor18.id = "citizen";
			pAsset = behaviourTaskActor18;
			this.t = behaviourTaskActor18;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(1f, 5f));
			this.t.addBeh(new BehFindRandomTile());
			this.t.addBeh(new BehGoToTileTarget());
			BehaviourTaskActor behaviourTaskActor19 = new BehaviourTaskActor();
			behaviourTaskActor19.id = "city_idle_walking";
			pAsset = behaviourTaskActor19;
			this.t = behaviourTaskActor19;
			this.add(pAsset);
			this.t.addBeh(new BehCityGetRandomZoneTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(3f, 6f));
			BehaviourTaskActor behaviourTaskActor20 = new BehaviourTaskActor();
			behaviourTaskActor20.id = "find_city_job";
			pAsset = behaviourTaskActor20;
			this.t = behaviourTaskActor20;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(1f, 5f));
			this.t.addBeh(new BehCityFindNewJob());
			BehaviourTaskActor behaviourTaskActor21 = new BehaviourTaskActor();
			behaviourTaskActor21.id = "look_for_animals";
			pAsset = behaviourTaskActor21;
			this.t = behaviourTaskActor21;
			this.add(pAsset);
			this.t.addBeh(new BehFindTargetForHunter());
			this.t.addBeh(new BehGoToActorTarget("sameTile", false));
			this.t.addBeh(new BehAttackActorTarget());
			BehaviourTaskActor behaviourTaskActor22 = new BehaviourTaskActor();
			behaviourTaskActor22.id = "convert_ore";
			pAsset = behaviourTaskActor22;
			this.t = behaviourTaskActor22;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("random_house_building"));
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehStayInBuildingTarget(10f, 15f));
			this.t.addBeh(new BehConvertOre());
			this.t.addBeh(new BehExitBuilding());
			this.t.addBeh(new BehUnloadResources());
			BehaviourTaskActor behaviourTaskActor23 = new BehaviourTaskActor();
			behaviourTaskActor23.id = "make_items";
			pAsset = behaviourTaskActor23;
			this.t = behaviourTaskActor23;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("random_house_building"));
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehStayInBuildingTarget(10f, 15f));
			this.t.addBeh(new BehMakeItem());
			this.t.addBeh(new BehExitBuilding());
			BehaviourTaskActor behaviourTaskActor24 = new BehaviourTaskActor();
			behaviourTaskActor24.id = "cleaning";
			behaviourTaskActor24.force_item_sprite = "tool_hammer";
			pAsset = behaviourTaskActor24;
			this.t = behaviourTaskActor24;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("ruins"));
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(0.3f, 0.3f));
			this.t.addBeh(new BehLookAtTarget("building_target"));
			this.t.addBeh(new BehAngleAnimation("building_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("building_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("building_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("building_target", 0f, 40f));
			this.t.addBeh(new BehRemoveRuins());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor25 = new BehaviourTaskActor();
			behaviourTaskActor25.id = "put_out_fire";
			behaviourTaskActor25.force_item_sprite = "tool_bucket";
			pAsset = behaviourTaskActor25;
			this.t = behaviourTaskActor25;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindFireZone());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehJumpingAnimation(1f));
			this.t.addBeh(new BehCityRemoveFire());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor26 = new BehaviourTaskActor();
			behaviourTaskActor26.id = "build_new_building";
			behaviourTaskActor26.force_item_sprite = "tool_hammer";
			pAsset = behaviourTaskActor26;
			this.t = behaviourTaskActor26;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("new_building"));
			this.t.addBeh(new BehFindConstructionTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehLookAtTarget("building_target"));
			this.t.addBeh(new BehAngleAnimation("building_target", 0f, 40f));
			this.t.addBeh(new BehBuildTargetProgress());
			this.t.addBeh(new BehRandomWait(0.5f, 1f));
			this.t.addBeh(new BehChuckTargetBuildProgress());
			BehaviourTaskActor behaviourTaskActor27 = new BehaviourTaskActor();
			behaviourTaskActor27.id = "build_road";
			behaviourTaskActor27.force_item_sprite = "tool_hammer";
			pAsset = behaviourTaskActor27;
			this.t = behaviourTaskActor27;
			this.add(pAsset);
			this.t.addBeh(new BehFindTile("new_road")
			{
				null_check_city = true
			});
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(0.2f, 1f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 0f, 40f));
			this.t.addBeh(new BehCityCreateRoad());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehRestartTask());
			BehaviourTaskActor behaviourTaskActor28 = new BehaviourTaskActor();
			behaviourTaskActor28.id = "collect_fruits";
			behaviourTaskActor28.force_item_sprite = "tool_basket";
			pAsset = behaviourTaskActor28;
			this.t = behaviourTaskActor28;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("fruitBush"));
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehLookAtTarget("building_target"));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(0f));
			this.t.addBeh(new BehExtractResourcesFromBuilding());
			this.t.addBeh(new BehRandomWait(2f, 3f));
			this.t.addBeh(new BehCityFindStorage());
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehUnloadResources());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehRestartTask());
			BehaviourTaskActor behaviourTaskActor29 = new BehaviourTaskActor();
			behaviourTaskActor29.id = "chop_trees";
			behaviourTaskActor29.force_item_sprite = "tool_axe";
			pAsset = behaviourTaskActor29;
			this.t = behaviourTaskActor29;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("trees"));
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehLookAtTarget("building_target"));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(0f));
			this.t.addBeh(new BehExtractResourcesFromBuilding());
			this.t.addBeh(new BehCityFindStorage());
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehUnloadResources());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor30 = new BehaviourTaskActor();
			behaviourTaskActor30.id = "mine_deposit";
			behaviourTaskActor30.force_item_sprite = "tool_pickaxe";
			pAsset = behaviourTaskActor30;
			this.t = behaviourTaskActor30;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("gold,ore,stone"));
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehLookAtTarget("building_target"));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(0f));
			this.t.addBeh(new BehExtractResourcesFromBuilding());
			this.t.addBeh(new BehCityFindStorage());
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehUnloadResources());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehRestartTask());
			BehaviourTaskActor behaviourTaskActor31 = new BehaviourTaskActor();
			behaviourTaskActor31.id = "farming_make_field";
			behaviourTaskActor31.force_item_sprite = "tool_hoe";
			pAsset = behaviourTaskActor31;
			this.t = behaviourTaskActor31;
			this.add(pAsset);
			this.t.addBeh(new BehFindTileForFarm());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehMakeFarm());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor32 = new BehaviourTaskActor();
			behaviourTaskActor32.id = "plant_crops";
			behaviourTaskActor32.force_item_sprite = "tool_hoe";
			pAsset = behaviourTaskActor32;
			this.t = behaviourTaskActor32;
			this.add(pAsset);
			this.t.addBeh(new BehFindFarmField());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehPlantCrops());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehRestartTask());
			BehaviourTaskActor behaviourTaskActor33 = new BehaviourTaskActor();
			behaviourTaskActor33.id = "harvest";
			behaviourTaskActor33.force_item_sprite = "tool_hoe";
			pAsset = behaviourTaskActor33;
			this.t = behaviourTaskActor33;
			this.add(pAsset);
			this.t.addBeh(new BehFindWheat());
			this.t.addBeh(new BehGoToBuildingTarget(false));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(0f));
			this.t.addBeh(new BehExtractResourcesFromBuilding());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehCityFindStorage());
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehUnloadResources());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehRestartTask());
			BehaviourTaskActor behaviourTaskActor34 = new BehaviourTaskActor();
			behaviourTaskActor34.id = "mine";
			behaviourTaskActor34.force_item_sprite = "tool_pickaxe";
			pAsset = behaviourTaskActor34;
			this.t = behaviourTaskActor34;
			this.add(pAsset);
			this.t.addBeh(new BehCityFindBuilding("mine"));
			this.t.addBeh(new BehGoToBuildingTarget(false));
			this.t.addBeh(new BehStayInBuildingTarget(10f, 15f));
			this.t.addBeh(new BehGetResourcesFromMine());
			this.t.addBeh(new BehExitBuilding());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehCityFindStorage());
			this.t.addBeh(new BehFindRandomFrontBuildingTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehUnloadResources());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehRestartTask());
			BehaviourTaskActor behaviourTaskActor35 = new BehaviourTaskActor();
			behaviourTaskActor35.id = "try_to_return_home";
			pAsset = behaviourTaskActor35;
			this.t = behaviourTaskActor35;
			this.add(pAsset);
			this.t.addBeh(new BehTaxiCheck());
			this.t.addBeh(new BehRandomWait(1f, 1f));
			this.t.addBeh(new BehTaxiFindShipTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehTaxiEmbark());
			BehaviourTaskActor behaviourTaskActor36 = new BehaviourTaskActor();
			behaviourTaskActor36.id = "warrior_check_city_army_group";
			pAsset = behaviourTaskActor36;
			this.t = behaviourTaskActor36;
			this.add(pAsset);
			this.t.addBeh(new BehCheckCityArmyGroup());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor37 = new BehaviourTaskActor();
			behaviourTaskActor37.id = "warrior_army_leader_move_random";
			pAsset = behaviourTaskActor37;
			this.t = behaviourTaskActor37;
			this.add(pAsset);
			this.t.addBeh(new BehFindRandomTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(10f, 20f));
			BehaviourTaskActor behaviourTaskActor38 = new BehaviourTaskActor();
			behaviourTaskActor38.id = "warrior_army_leader_move_to_attack_target";
			pAsset = behaviourTaskActor38;
			this.t = behaviourTaskActor38;
			this.add(pAsset);
			this.t.addBeh(new BehCityCheckAttack());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 4f));
			BehaviourTaskActor behaviourTaskActor39 = new BehaviourTaskActor();
			behaviourTaskActor39.id = "warrior_army_follow_leader";
			pAsset = behaviourTaskActor39;
			this.t = behaviourTaskActor39;
			this.add(pAsset);
			this.t.addBeh(new BehFindTileNearbyGroupLeader());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor40 = new BehaviourTaskActor();
			behaviourTaskActor40.id = "check_warrior_transport";
			pAsset = behaviourTaskActor40;
			this.t = behaviourTaskActor40;
			this.add(pAsset);
			this.t.addBeh(new BehCityWarriorTaxiCheck());
			this.t.addBeh(new BehRandomWait(1f, 5f));
			this.t.addBeh(new BehTaxiFindShipTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehTaxiEmbark());
			BehaviourTaskActor behaviourTaskActor41 = new BehaviourTaskActor();
			behaviourTaskActor41.id = "settler_same_island";
			pAsset = behaviourTaskActor41;
			this.t = behaviourTaskActor41;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(1f, 1f));
			this.t.addBeh(new BehCitySettlerFindTileSameIsland());
			this.t.addBeh(new BehGoToTileTarget());
			BehaviourTaskActor behaviourTaskActor42 = new BehaviourTaskActor();
			behaviourTaskActor42.id = "sit_inside_boat";
			pAsset = behaviourTaskActor42;
			this.t = behaviourTaskActor42;
			this.add(pAsset);
			this.t.addBeh(new BehTaxiEmbark());
			BehaviourTaskActor behaviourTaskActor43 = new BehaviourTaskActor();
			behaviourTaskActor43.id = "settler_check_transport";
			pAsset = behaviourTaskActor43;
			this.t = behaviourTaskActor43;
			this.add(pAsset);
			this.t.addBeh(new BehCitySettlerTaxiCheck());
			this.t.addBeh(new BehRandomWait(1f, 5f));
			this.t.addBeh(new BehTaxiFindShipTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehTaxiEmbark());
			BehaviourTaskActor behaviourTaskActor44 = new BehaviourTaskActor();
			behaviourTaskActor44.id = "wait";
			pAsset = behaviourTaskActor44;
			this.t = behaviourTaskActor44;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(1f, 1f));
			BehaviourTaskActor behaviourTaskActor45 = new BehaviourTaskActor();
			behaviourTaskActor45.id = "wait5";
			pAsset = behaviourTaskActor45;
			this.t = behaviourTaskActor45;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(1f, 5f));
			BehaviourTaskActor behaviourTaskActor46 = new BehaviourTaskActor();
			behaviourTaskActor46.id = "wait10";
			pAsset = behaviourTaskActor46;
			this.t = behaviourTaskActor46;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(1f, 10f));
		}

		// Token: 0x060013D1 RID: 5073 RVA: 0x000A59AC File Offset: 0x000A3BAC
		private void initTasksMobs()
		{
			BehaviourTaskActor behaviourTaskActor = new BehaviourTaskActor();
			behaviourTaskActor.id = "check_hunger_animal";
			BehaviourTaskActor pAsset = behaviourTaskActor;
			this.t = behaviourTaskActor;
			this.add(pAsset);
			this.t.addBeh(new BehCheckHunger());
			this.t.addBeh(new BehCheckHunger());
			this.t.addBeh(new BehCheckHunger());
			BehaviourTaskActor behaviourTaskActor2 = new BehaviourTaskActor();
			behaviourTaskActor2.id = "eat_fruits";
			pAsset = behaviourTaskActor2;
			this.t = behaviourTaskActor2;
			this.add(pAsset);
			this.t.addBeh(new BehFindBuilding("fruits"));
			this.t.addBeh(new BehGoToBuildingTarget(false));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehConsumeTargetBuilding());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor3 = new BehaviourTaskActor();
			behaviourTaskActor3.id = "eat_flowers";
			pAsset = behaviourTaskActor3;
			this.t = behaviourTaskActor3;
			this.add(pAsset);
			this.t.addBeh(new BehFindTile("flowers"));
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehConsumeFlowers());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor4 = new BehaviourTaskActor();
			behaviourTaskActor4.id = "eat_crops";
			pAsset = behaviourTaskActor4;
			this.t = behaviourTaskActor4;
			this.add(pAsset);
			this.t.addBeh(new BehFindBuilding("crops"));
			this.t.addBeh(new BehGoToBuildingTarget(false));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehResourceGatheringAnimation(1f));
			this.t.addBeh(new BehConsumeTargetBuilding());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor5 = new BehaviourTaskActor();
			behaviourTaskActor5.id = "eat_grass";
			pAsset = behaviourTaskActor5;
			this.t = behaviourTaskActor5;
			this.add(pAsset);
			this.t.addBeh(new BehFindTile("grass"));
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 40f));
			this.t.addBeh(new BehConsumeGrass());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			BehaviourTaskActor behaviourTaskActor6 = new BehaviourTaskActor();
			behaviourTaskActor6.id = "hunting_attack";
			pAsset = behaviourTaskActor6;
			this.t = behaviourTaskActor6;
			this.add(pAsset);
			this.t.addBeh(new BehFindMeatSource());
			this.t.addBeh(new BehGoToActorTarget("sameTile", false));
			this.t.addBeh(new BehConsumeActorTarget());
			BehaviourTaskActor behaviourTaskActor7 = new BehaviourTaskActor();
			behaviourTaskActor7.id = "try_babymaking";
			pAsset = behaviourTaskActor7;
			this.t = behaviourTaskActor7;
			this.add(pAsset);
			this.t.addBeh(new BehTryBabymaking());
			BehaviourTaskActor behaviourTaskActor8 = new BehaviourTaskActor();
			behaviourTaskActor8.id = "babymaking";
			pAsset = behaviourTaskActor8;
			this.t = behaviourTaskActor8;
			this.add(pAsset);
			this.t.addBeh(new BehGoToActorTarget("sameTile", false));
			this.t.addBeh(new BehRandomWait(0.5f, 1f));
			this.t.addBeh(new BehBabymakingTime());
			this.t.addBeh(new BehRandomWait(0.5f, 1f));
			this.t.addBeh(new BehBabymakingTime());
			this.t.addBeh(new BehRandomWait(0.5f, 1f));
			this.t.addBeh(new BehBabymakingTime());
			this.t.addBeh(new BehRandomWait(0.5f, 1f));
			this.t.addBeh(new BehMakeBaby());
			this.t.addBeh(new BehRandomWait(1f, 3f));
			BehaviourTaskActor behaviourTaskActor9 = new BehaviourTaskActor();
			behaviourTaskActor9.id = "follow_same_race";
			pAsset = behaviourTaskActor9;
			this.t = behaviourTaskActor9;
			this.add(pAsset);
			this.t.addBeh(new BehFindSameRaceActor());
			this.t.addBeh(new BehGoToActorTarget("sameRegion", false));
			BehaviourTaskActor behaviourTaskActor10 = new BehaviourTaskActor();
			behaviourTaskActor10.id = "attack_golden_brain";
			pAsset = behaviourTaskActor10;
			this.t = behaviourTaskActor10;
			this.add(pAsset);
			this.t.addBeh(new BehFindGoldenBrain());
			this.t.addBeh(new BehGoToBuildingTarget(false));
			BehaviourTaskActor behaviourTaskActor11 = new BehaviourTaskActor();
			behaviourTaskActor11.id = "rat";
			pAsset = behaviourTaskActor11;
			this.t = behaviourTaskActor11;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(1f, 1f));
			this.t.addBeh(new BehSpecialRat());
			this.t.addBeh(new BehGoToTileTarget());
			BehaviourTaskActor behaviourTaskActor12 = new BehaviourTaskActor();
			behaviourTaskActor12.id = "crab";
			pAsset = behaviourTaskActor12;
			this.t = behaviourTaskActor12;
			this.add(pAsset);
			this.t.addBeh(new BehAnimalCheckHungry());
			this.t.addBeh(new BehRandomWait(2f, 5f));
			this.t.addBeh(new BehFindTileBeach());
			this.t.addBeh(new BehGoOrSwimToTileTarget());
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 20f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 20f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 20f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 20f));
			this.t.addBeh(new BehReplenishHunger());
			BehaviourTaskActor behaviourTaskActor13 = new BehaviourTaskActor();
			behaviourTaskActor13.id = "crab_danger_check";
			pAsset = behaviourTaskActor13;
			this.t = behaviourTaskActor13;
			this.add(pAsset);
			this.t.addBeh(new BehCheckIfOnGround());
			this.t.addBeh(new BehActiveCrabDangerCheck());
			BehaviourTaskActor behaviourTaskActor14 = new BehaviourTaskActor();
			behaviourTaskActor14.id = "water_feeding";
			pAsset = behaviourTaskActor14;
			this.t = behaviourTaskActor14;
			this.add(pAsset);
			this.t.addBeh(new BehAnimalCheckHungry());
			this.t.addBeh(new BehFindTile("water"));
			this.t.addBeh(new BehGoOrSwimToTileTarget());
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 20f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 20f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 20f));
			this.t.addBeh(new BehAngleAnimation("tile_target", 1f, 20f));
			this.t.addBeh(new BehReplenishHunger());
			BehaviourTaskActor behaviourTaskActor15 = new BehaviourTaskActor();
			behaviourTaskActor15.id = "crab_burrow";
			pAsset = behaviourTaskActor15;
			this.t = behaviourTaskActor15;
			this.add(pAsset);
			this.t.addBeh(new BehCheckIfOnGround());
			this.t.addBeh(new BehFindRandomTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehCrabBurrow());
			BehaviourTaskActor behaviourTaskActor16 = new BehaviourTaskActor();
			behaviourTaskActor16.id = "make_skeleton";
			pAsset = behaviourTaskActor16;
			this.t = behaviourTaskActor16;
			this.add(pAsset);
			this.t.addBeh(new BehMagicMakeSkeleton());
			this.t.addBeh(new BehRandomWait(3f, 3f));
			BehaviourTaskActor behaviourTaskActor17 = new BehaviourTaskActor();
			behaviourTaskActor17.id = "skeleton_move";
			pAsset = behaviourTaskActor17;
			this.t = behaviourTaskActor17;
			this.add(pAsset);
			this.t.addBeh(new BehSkeletonFindTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(3f, 6f));
			BehaviourTaskActor behaviourTaskActor18 = new BehaviourTaskActor();
			behaviourTaskActor18.id = "spawn_grass_seeds";
			pAsset = behaviourTaskActor18;
			this.t = behaviourTaskActor18;
			this.add(pAsset);
			this.t.addBeh(new BehSpawnGrassSeeds());
			this.t.addBeh(new BehRandomWait(1f, 3f));
			BehaviourTaskActor behaviourTaskActor19 = new BehaviourTaskActor();
			behaviourTaskActor19.id = "check_cure";
			pAsset = behaviourTaskActor19;
			this.t = behaviourTaskActor19;
			this.add(pAsset);
			this.t.addBeh(new BehCheckCure());
			this.t.addBeh(new BehRandomWait(1f, 3f));
			BehaviourTaskActor behaviourTaskActor20 = new BehaviourTaskActor();
			behaviourTaskActor20.id = "burn_tumors";
			pAsset = behaviourTaskActor20;
			this.t = behaviourTaskActor20;
			this.add(pAsset);
			this.t.addBeh(new BehBurnTumorTiles());
			this.t.addBeh(new BehRandomWait(1f, 3f));
			BehaviourTaskActor behaviourTaskActor21 = new BehaviourTaskActor();
			behaviourTaskActor21.id = "check_heal";
			pAsset = behaviourTaskActor21;
			this.t = behaviourTaskActor21;
			this.add(pAsset);
			this.t.addBeh(new BehHeal());
			this.t.addBeh(new BehRandomWait(1f, 3f));
			BehaviourTaskActor behaviourTaskActor22 = new BehaviourTaskActor();
			behaviourTaskActor22.id = "random_teleport";
			pAsset = behaviourTaskActor22;
			this.t = behaviourTaskActor22;
			this.add(pAsset);
			this.t.addBeh(new BehRandomTeleport());
			this.t.addBeh(new BehRandomWait(0.5f, 1f));
			BehaviourTaskActor behaviourTaskActor23 = new BehaviourTaskActor();
			behaviourTaskActor23.id = "run_to_water";
			pAsset = behaviourTaskActor23;
			this.t = behaviourTaskActor23;
			this.add(pAsset);
			this.t.addBeh(new BehFindTileWhenOnFire());
			this.t.addBeh(new BehGoOrSwimToTileTarget());
			BehaviourTaskActor behaviourTaskActor24 = new BehaviourTaskActor();
			behaviourTaskActor24.id = "short_move";
			pAsset = behaviourTaskActor24;
			this.t = behaviourTaskActor24;
			this.add(pAsset);
			this.t.addBeh(new BehShortRandomMove());
			this.t.addBeh(new BehGoToTileTarget());
		}

		// Token: 0x060013D2 RID: 5074 RVA: 0x000A64D4 File Offset: 0x000A46D4
		private void initTasksBoats()
		{
			BehaviourTaskActor behaviourTaskActor = new BehaviourTaskActor();
			behaviourTaskActor.id = "boat_idle";
			BehaviourTaskActor pAsset = behaviourTaskActor;
			this.t = behaviourTaskActor;
			this.add(pAsset);
			this.t.addBeh(new BehBoatDamageCheck());
			this.t.addBeh(new BehBoatFindOceanNeutralTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(3f, 10f));
			BehaviourTaskActor behaviourTaskActor2 = new BehaviourTaskActor();
			behaviourTaskActor2.id = "boat_danger_check";
			pAsset = behaviourTaskActor2;
			this.t = behaviourTaskActor2;
			this.add(pAsset);
			this.t.addBeh(new BehCheckIfInLiquid());
			this.t.addBeh(new BehBoatDangerCheck());
			this.t.addBeh(new BehBoatFindWaterTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(3f, 10f));
			BehaviourTaskActor behaviourTaskActor3 = new BehaviourTaskActor();
			behaviourTaskActor3.id = "boat_transport_check";
			pAsset = behaviourTaskActor3;
			this.t = behaviourTaskActor3;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(0f, 1f));
			this.t.addBeh(new BehBoatTransportCheck());
			BehaviourTaskActor behaviourTaskActor4 = new BehaviourTaskActor();
			behaviourTaskActor4.id = "boat_transport_check_taxi";
			pAsset = behaviourTaskActor4;
			this.t = behaviourTaskActor4;
			this.add(pAsset);
			this.t.addBeh(new BehBoatFindRequest());
			BehaviourTaskActor behaviourTaskActor5 = new BehaviourTaskActor();
			behaviourTaskActor5.id = "boat_transport_go_load";
			pAsset = behaviourTaskActor5;
			this.t = behaviourTaskActor5;
			this.add(pAsset);
			this.t.addBeh(new BehBoatTransportFindTilePickUp());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(0f, 1f));
			this.t.addBeh(new BehBoatTransportDoLoading());
			this.t.addBeh(new BehSetNextTask("boat_transport_go_unload", false));
			BehaviourTaskActor behaviourTaskActor6 = new BehaviourTaskActor();
			behaviourTaskActor6.id = "boat_transport_go_unload";
			pAsset = behaviourTaskActor6;
			this.t = behaviourTaskActor6;
			this.add(pAsset);
			this.t.addBeh(new BehRandomWait(0f, 1f));
			this.t.addBeh(new BehBoatTransportFindTileUnload());
			this.t.addBeh(new BehGoToTileTarget
			{
				walkOnWater = true
			});
			this.t.addBeh(new BehRandomWait(0f, 1f));
			this.t.addBeh(new BehBoatTransportUnloadUnits());
			this.t.addBeh(new BehRandomWait(3f, 10f));
			this.t.addBeh(new BehEndJob());
			BehaviourTaskActor behaviourTaskActor7 = new BehaviourTaskActor();
			behaviourTaskActor7.id = "boat_trading";
			pAsset = behaviourTaskActor7;
			this.t = behaviourTaskActor7;
			this.add(pAsset);
			this.t.addBeh(new BehBoatCheckHomeDocks());
			this.t.addBeh(new BehBoatFindTargetForTrade());
			this.t.addBeh(new BehBoatFindTileInDock());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehStayInBuildingTarget(2f, 5f));
			this.t.addBeh(new BehBoatMakeTrade());
			this.t.addBeh(new BehExitBuilding());
			this.t.addBeh(new BehSetNextTask("boat_return_to_dock", true));
			BehaviourTaskActor behaviourTaskActor8 = new BehaviourTaskActor();
			behaviourTaskActor8.id = "boat_fishing";
			pAsset = behaviourTaskActor8;
			this.t = behaviourTaskActor8;
			this.add(pAsset);
			this.t.addBeh(new BehBoatCheckHomeDocks());
			this.t.addBeh(new BehBoatFindWaterTile());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(0f, 1f));
			this.t.addBeh(new BehBoatFishing());
			this.t.addBeh(new BehRandomWait(5f, 10f));
			this.t.addBeh(new BehBoatCollectFish());
			this.t.addBeh(new BehRandomWait(1f, 2f));
			this.t.addBeh(new BehBoatCheckFishingRepeat());
			BehaviourTaskActor behaviourTaskActor9 = new BehaviourTaskActor();
			behaviourTaskActor9.id = "boat_return_to_dock";
			pAsset = behaviourTaskActor9;
			this.t = behaviourTaskActor9;
			this.add(pAsset);
			this.t.addBeh(new BehBoatCheckHomeDocks());
			this.t.addBeh(new BehBoatSetHomeDockTarget());
			this.t.addBeh(new BehBoatFindTileInDock());
			this.t.addBeh(new BehGoToTileTarget());
			this.t.addBeh(new BehRandomWait(0f, 3f));
			this.t.addBeh(new BehStayInBuildingTarget(2f, 4f));
			this.t.addBeh(new BehUnloadResources());
			this.t.addBeh(new BehRepairInDock());
			this.t.addBeh(new BehExitBuilding());
			this.t.addBeh(new BehEndJob());
		}
	}
}
